// Ensure the helper generated by some bundlers (like esbuild) is available globally.
if (typeof globalThis !== 'undefined' && typeof (globalThis as any).__publicField !== 'function') {
  (globalThis as any).__publicField = (obj: any, key: string, value: any) => {
    try {
      Object.defineProperty(obj, key, {
        enumerable: true,
        configurable: true,
        writable: true,
        value
      });
    } catch {
      obj[key] = value;
    }
    return value;
  };
}

