// Ensure the helper generated by some bundlers (like esbuild) is available globally.
if (typeof globalThis !== 'undefined' && typeof (globalThis as any).__publicField !== 'function') {
  (globalThis as any).__publicField = (obj: any, key: string, value: any) => {
    // Safely handle undefined/null objects - return early
    if (obj == null || typeof obj !== 'object') {
      return value;
    }
    try {
      Object.defineProperty(obj, key, {
        enumerable: true,
        configurable: true,
        writable: true,
        value
      });
    } catch {
      if (obj != null) obj[key] = value;
    }
    return value;
  };
}

