import { uploadProducts, getAllProducts, } from "../lib/database.js";
export async function seedProduk() {
    console.log("🚀 Menjalankan seed produk penuh...");
    // Bersihin dulu semua data biar isi baru
    // await deleteAllProducts();
    // Upload data produk baru
    const products = [
        // KULINER
        {
            ASIN: "IDFOOD001",
            nama_produk: "Sambal Bawang Rumahan Pedas Nikmat 200gr",
            merek_produk: "Mak Bawang",
            model_produk: "SB-200",
            kategori: "Kuliner",
            sub_kategori: "Sambal",
            harga_asli: 30000,
            harga_produk: 25000,
            persentase_diskon: 17,
            mata_uang: "IDR",
            jumlah_unit: 120,
            unit_terjual: 420,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 200,
            bahan: "Cabai, Bawang Merah, Minyak Kelapa",
            varian_produk: "200gr",
            negara_asal: "Indonesia",
            spesifikasi: "Sambal pedas buatan rumahan tanpa pengawet",
            deskripsi_produk: "Sambal bawang khas Jawa Timur dengan cita rasa pedas dan gurih, cocok untuk semua masakan.",
            keyword: "sambal, pedas, rumahan",
            gambar_produk: "https://example.com/sambal1.jpg",
            thumbnail_produk: "https://example.com/sambal1-thumb.jpg",
            toko: "Dapur Nusantara",
            rating_toko: 4.8,
            status_toko: "Toko Biasa",
            lokasi_toko: "Surabaya, Indonesia",
            rating_bintang: 4.7,
            jumlah_ulasan: 320,
        },
        {
            ASIN: "IDFOOD002",
            nama_produk: "Keripik Tempe Original 100gr",
            merek_produk: "TempeKriuk",
            model_produk: "TK-100",
            kategori: "Kuliner",
            sub_kategori: "Snack Tradisional",
            harga_asli: 15000,
            harga_produk: 12000,
            persentase_diskon: 20,
            mata_uang: "IDR",
            jumlah_unit: 300,
            unit_terjual: 980,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 100,
            bahan: "Tempe kedelai, garam, bumbu alami",
            negara_asal: "Indonesia",
            spesifikasi: "Keripik tempe renyah khas Malang",
            deskripsi_produk: "Cemilan tradisional tempe renyah dan gurih. Cocok buat teman kopi.",
            keyword: "keripik, tempe, snack",
            gambar_produk: "https://example.com/keripik-tempe.jpg",
            thumbnail_produk: "https://example.com/keripik-tempe-thumb.jpg",
            toko: "OlehOleh Malang",
            rating_toko: 4.6,
            status_toko: "Official Store",
            lokasi_toko: "Malang, Indonesia",
            rating_bintang: 4.8,
            jumlah_ulasan: 540,
        },
        // Jasa
        {
            ASIN: "SRV001",
            nama_produk: "Jasa Desain Logo Profesional",
            merek_produk: "Kreatif Studio",
            model_produk: "LogoCustom2025",
            kategori: "Jasa",
            sub_kategori: "Desain Grafis",
            harga_asli: 300000,
            harga_produk: 250000,
            persentase_diskon: 17,
            mata_uang: "IDR",
            jumlah_unit: 9999,
            unit_terjual: 128,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 0.1,
            deskripsi_produk: "Layanan desain logo profesional untuk bisnis Anda. Hasil cepat, revisi tak terbatas.",
            keyword: "desain, logo, jasa kreatif",
            gambar_produk: "https://example.com/jasa-logo.jpg",
            thumbnail_produk: "https://example.com/jasa-logo-thumb.jpg",
            toko: "Kreatif Studio",
            rating_toko: 4.9,
            status_toko: "Official Store",
            lokasi_toko: "Jakarta",
            jumlah_produk_di_toko: 23,
            rating_bintang: 4.8,
            jumlah_ulasan: 92,
            komentar: ["Desainnya keren banget!", "Cepat dan komunikatif."],
            foto_pembeli: [],
        },
        {
            ASIN: "SRV002",
            nama_produk: "Jasa Fotografi Produk",
            merek_produk: "LensArt Studio",
            model_produk: "PhotoProLite",
            kategori: "Jasa",
            sub_kategori: "Fotografi",
            harga_asli: 800000,
            harga_produk: 700000,
            persentase_diskon: 12,
            mata_uang: "IDR",
            jumlah_unit: 9999,
            unit_terjual: 75,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 0.2,
            deskripsi_produk: "Jasa pemotretan produk dengan hasil profesional. Termasuk editing dan lighting setup.",
            keyword: "jasa foto, produk, photography",
            gambar_produk: "https://example.com/jasa-foto.jpg",
            thumbnail_produk: "https://example.com/jasa-foto-thumb.jpg",
            toko: "LensArt Studio",
            rating_toko: 4.7,
            status_toko: "Toko Biasa",
            lokasi_toko: "Bandung",
            jumlah_produk_di_toko: 12,
            rating_bintang: 4.6,
            jumlah_ulasan: 40,
            komentar: ["Foto produk saya jadi keren banget!", "Worth it banget untuk harga segini."],
            foto_pembeli: [],
        },
        // KESEHATAN
        {
            ASIN: "IDHEALTH001",
            nama_produk: "Minyak Kayu Putih Cap Lang 60ml",
            merek_produk: "Cap Lang",
            model_produk: "MKP-60",
            kategori: "Kesehatan",
            sub_kategori: "Minyak Gosok",
            harga_asli: 28000,
            harga_produk: 24000,
            persentase_diskon: 14,
            mata_uang: "IDR",
            jumlah_unit: 500,
            unit_terjual: 1600,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 60,
            deskripsi_produk: "Minyak kayu putih asli untuk menghangatkan tubuh, meredakan gatal dan masuk angin.",
            gambar_produk: "https://example.com/minyak-kayu-putih.jpg",
            thumbnail_produk: "https://example.com/minyak-kayu-putih-thumb.jpg",
            toko: "Apotek Sehat",
            rating_toko: 4.9,
            status_toko: "Official Store",
            lokasi_toko: "Jakarta, Indonesia",
            rating_bintang: 4.9,
            jumlah_ulasan: 1020,
        },
        {
            ASIN: "IDHEALTH002",
            nama_produk: "Masker Wajah Spirulina Original 50gr",
            merek_produk: "NatureSkin",
            model_produk: "MASK-SPRL",
            kategori: "Kesehatan",
            sub_kategori: "Perawatan Wajah",
            harga_asli: 90000,
            harga_produk: 65000,
            persentase_diskon: 28,
            mata_uang: "IDR",
            jumlah_unit: 200,
            unit_terjual: 350,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 50,
            deskripsi_produk: "Masker alami dari spirulina yang membantu mencerahkan kulit dan mengurangi jerawat.",
            toko: "NatureSkin Official",
            rating_toko: 4.8,
            status_toko: "Official Store",
            lokasi_toko: "Bandung, Indonesia",
            rating_bintang: 4.8,
            jumlah_ulasan: 500,
            gambar_produk: "https://example.com/masker-spirulina.jpg",
            thumbnail_produk: "https://example.com/masker-spirulina-thumb.jpg",
        },
        // Fashion
        {
            ASIN: "FAS001",
            nama_produk: "Kaos Oversized Unisex",
            merek_produk: "UrbanStyle",
            model_produk: "OVR2025",
            kategori: "Fashion",
            sub_kategori: "Atasan",
            harga_asli: 150000,
            harga_produk: 99000,
            persentase_diskon: 34,
            mata_uang: "IDR",
            jumlah_unit: 120,
            unit_terjual: 70,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 0.3,
            bahan: "Katun combed 30s",
            warna: "Hitam",
            varian_produk: "S, M, L, XL",
            deskripsi_produk: "Kaos oversized dengan bahan lembut dan potongan santai, cocok untuk gaya kasual.",
            keyword: "kaos, oversized, unisex",
            gambar_produk: "https://example.com/kaos-oversized.jpg",
            thumbnail_produk: "https://example.com/kaos-oversized-thumb.jpg",
            toko: "UrbanStyle Official",
            rating_toko: 4.8,
            status_toko: "Official Store",
            lokasi_toko: "Jakarta",
            jumlah_produk_di_toko: 45,
            rating_bintang: 4.7,
            jumlah_ulasan: 180,
            komentar: ["Bahannya adem banget!", "Ukuran pas dan nyaman."],
            foto_pembeli: [],
        },
        {
            ASIN: "FAS002",
            nama_produk: "Celana Cargo Streetwear",
            merek_produk: "StreetMode",
            model_produk: "CargoFlex",
            kategori: "Fashion",
            sub_kategori: "Bawahan",
            harga_asli: 250000,
            harga_produk: 199000,
            persentase_diskon: 20,
            mata_uang: "IDR",
            jumlah_unit: 80,
            unit_terjual: 45,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 0.5,
            bahan: "Ripstop Cotton",
            warna: "Army Green",
            varian_produk: "M, L, XL",
            deskripsi_produk: "Celana cargo trendi dengan banyak kantong dan bahan kuat, cocok untuk kegiatan outdoor.",
            keyword: "celana, cargo, streetwear",
            gambar_produk: "https://example.com/cargo-streetwear.jpg",
            thumbnail_produk: "https://example.com/cargo-streetwear-thumb.jpg",
            toko: "StreetMode Store",
            rating_toko: 4.6,
            status_toko: "Toko Biasa",
            lokasi_toko: "Bandung",
            jumlah_produk_di_toko: 33,
            rating_bintang: 4.5,
            jumlah_ulasan: 60,
            komentar: ["Kualitas bagus, kuat dipakai hiking.", "Modelnya keren banget!"],
            foto_pembeli: [],
        },
        // PERTANIAN
        {
            ASIN: "IDAGRI001",
            nama_produk: "Bibit Cabai Rawit Super Tahan Hama",
            merek_produk: "TaniJaya",
            model_produk: "BIBIT-CB01",
            kategori: "Pertanian",
            sub_kategori: "Bibit Tanaman",
            harga_asli: 20000,
            harga_produk: 15000,
            persentase_diskon: 25,
            mata_uang: "IDR",
            jumlah_unit: 500,
            unit_terjual: 800,
            status_produk: "Tersedia",
            minimum_pemesanan: 2,
            kondisi_produk: "Baru",
            berat_satuan: 100,
            deskripsi_produk: "Bibit cabai rawit unggul, cepat panen, cocok untuk semua jenis tanah.",
            toko: "TaniJaya Farm",
            rating_toko: 4.7,
            status_toko: "Toko Biasa",
            lokasi_toko: "Sleman, Indonesia",
            rating_bintang: 4.8,
            jumlah_ulasan: 290,
            gambar_produk: "https://example.com/bibit-cabai.jpg",
            thumbnail_produk: "https://example.com/bibit-cabai-thumb.jpg",
        },
        {
            ASIN: "IDAGRI002",
            nama_produk: "Pupuk Organik Cair 1 Liter",
            merek_produk: "BioGrow",
            model_produk: "BIOG-1L",
            kategori: "Pertanian",
            sub_kategori: "Pupuk",
            harga_asli: 40000,
            harga_produk: 32000,
            persentase_diskon: 20,
            mata_uang: "IDR",
            jumlah_unit: 300,
            unit_terjual: 600,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 1000,
            deskripsi_produk: "Pupuk cair alami yang membantu pertumbuhan akar dan daun secara maksimal.",
            toko: "BioGrow Indonesia",
            rating_toko: 4.8,
            status_toko: "Official Store",
            lokasi_toko: "Bogor, Indonesia",
            rating_bintang: 4.9,
            jumlah_ulasan: 480,
            gambar_produk: "https://example.com/pupuk-cair.jpg",
            thumbnail_produk: "https://example.com/pupuk-cair-thumb.jpg",
        },
        // ELEKTRONIK
        {
            ASIN: "IDELEC001",
            nama_produk: "Headset Bluetooth TWS V5.1",
            merek_produk: "SoundPro",
            model_produk: "SP-TWS51",
            kategori: "Elektronik",
            sub_kategori: "Audio",
            harga_asli: 250000,
            harga_produk: 179000,
            persentase_diskon: 28,
            mata_uang: "IDR",
            jumlah_unit: 150,
            unit_terjual: 420,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 120,
            deskripsi_produk: "Headset wireless dengan suara jernih, baterai tahan lama, dan fitur touch control.",
            toko: "GadgetOne",
            rating_toko: 4.7,
            status_toko: "Official Store",
            lokasi_toko: "Jakarta, Indonesia",
            rating_bintang: 4.8,
            jumlah_ulasan: 350,
            gambar_produk: "https://example.com/headset-tws.jpg",
            thumbnail_produk: "https://example.com/headset-tws-thumb.jpg",
        },
        {
            ASIN: "IDELEC002",
            nama_produk: "Smart LED Bulb 9W WiFi RGB",
            merek_produk: "LuminaTech",
            model_produk: "LT-9RGB",
            kategori: "Elektronik",
            sub_kategori: "Lampu Pintar",
            harga_asli: 120000,
            harga_produk: 95000,
            persentase_diskon: 21,
            mata_uang: "IDR",
            jumlah_unit: 180,
            unit_terjual: 310,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 200,
            deskripsi_produk: "Lampu pintar RGB yang bisa dikontrol lewat aplikasi HP dan suara (Google/Alexa).",
            toko: "TechHome ID",
            rating_toko: 4.9,
            status_toko: "Official Store",
            lokasi_toko: "Tangerang, Indonesia",
            rating_bintang: 4.9,
            jumlah_ulasan: 600,
            gambar_produk: "https://example.com/lampu-rgb.jpg",
            thumbnail_produk: "https://example.com/lampu-rgb-thumb.jpg",
        },
        // FURNITURE
        {
            ASIN: "IDFURN001",
            nama_produk: "Meja Belajar Lipat Kayu Jati",
            merek_produk: "JeparaCraft",
            model_produk: "JCR-MB01",
            kategori: "Furniture",
            sub_kategori: "Meja",
            harga_asli: 450000,
            harga_produk: 375000,
            persentase_diskon: 17,
            mata_uang: "IDR",
            jumlah_unit: 60,
            unit_terjual: 130,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 8000,
            bahan: "Kayu Jati",
            deskripsi_produk: "Meja belajar lipat dari kayu jati asli, kokoh dan tahan lama.",
            toko: "JeparaCraft",
            rating_toko: 4.9,
            status_toko: "Toko Biasa",
            lokasi_toko: "Jepara, Indonesia",
            rating_bintang: 4.9,
            jumlah_ulasan: 210,
            gambar_produk: "https://example.com/meja-belajar.jpg",
            thumbnail_produk: "https://example.com/meja-belajar-thumb.jpg",
        },
        {
            ASIN: "IDFURN002",
            nama_produk: "Rak Buku Minimalis 4 Susun",
            merek_produk: "InnoSpace",
            model_produk: "RKM-4S",
            kategori: "Furniture",
            sub_kategori: "Rak",
            harga_asli: 320000,
            harga_produk: 275000,
            persentase_diskon: 14,
            mata_uang: "IDR",
            jumlah_unit: 100,
            unit_terjual: 280,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 5000,
            bahan: "MDF + Besi",
            deskripsi_produk: "Rak buku minimalis dengan desain modern dan kuat menahan beban.",
            toko: "InnoSpace Furniture",
            rating_toko: 4.8,
            status_toko: "Official Store",
            lokasi_toko: "Bekasi, Indonesia",
            rating_bintang: 4.8,
            jumlah_ulasan: 340,
            gambar_produk: "https://example.com/rak-buku.jpg",
            thumbnail_produk: "https://example.com/rak-buku-thumb.jpg",
        },
        // EDUKASI
        {
            ASIN: "IDEDU001",
            nama_produk: "Kelas Online Desain Grafis Pemula",
            merek_produk: "SkillHub",
            model_produk: "CLS-DESIGN01",
            kategori: "Edukasi",
            sub_kategori: "Kursus Online",
            harga_asli: 500000,
            harga_produk: 350000,
            persentase_diskon: 30,
            mata_uang: "IDR",
            jumlah_unit: 9999,
            unit_terjual: 650,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 0,
            deskripsi_produk: "Belajar desain grafis dari nol, cocok untuk pemula dan freelance.",
            toko: "SkillHub ID",
            rating_toko: 4.9,
            status_toko: "Official Store",
            lokasi_toko: "Online",
            rating_bintang: 4.8,
            jumlah_ulasan: 410,
            gambar_produk: "https://example.com/kelas-desain.jpg",
            thumbnail_produk: "https://example.com/kelas-desain-thumb.jpg",
        },
        {
            ASIN: "IDEDU002",
            nama_produk: "Buku ‘Bisnis UMKM dari Nol’",
            merek_produk: "Gramedia",
            model_produk: "BOOK-UMKM01",
            kategori: "Edukasi",
            sub_kategori: "Buku Bisnis",
            harga_asli: 120000,
            harga_produk: 99000,
            persentase_diskon: 18,
            mata_uang: "IDR",
            jumlah_unit: 200,
            unit_terjual: 350,
            status_produk: "Tersedia",
            minimum_pemesanan: 1,
            kondisi_produk: "Baru",
            berat_satuan: 400,
            deskripsi_produk: "Panduan lengkap membangun bisnis UMKM dari nol dengan strategi modern.",
            toko: "Gramedia Official",
            rating_toko: 4.9,
            status_toko: "Official Store",
            lokasi_toko: "Jakarta, Indonesia",
            rating_bintang: 4.8,
            jumlah_ulasan: 250,
            gambar_produk: "https://example.com/buku-umkm.jpg",
            thumbnail_produk: "https://example.com/buku-umkm-thumb.jpg",
        },
    ];
    await uploadProducts(products);
    // 🔍 Cek semua produk setelah upload
    let all = await getAllProducts();
    console.log("📦 Produk setelah upload:");
    console.table(all);
    // Update satu produk
    // if (all.length > 0) {
    //   await updateProduct(all[0].id, {
    //     nama_produk: "Shampo Herbal Premium",
    //     harga_produk: 59900,
    //     jumlah_unit: 50,
    //   });
    // }
    // BulkUpdate (buat update pake mapping)
    // if (all.length >= 2) {
    //   await bulkUpdateProducts([
    //     { id: all[0].id, data: { persentase_diskon: 10, harga_produk: 54900 } },
    //     { id: all[1].id, data: { status_produk: "Habis", unit_terjual: 2000 } },
    //   ]);
    // }
    // Hapus satu produk
    // if (all.length > 0) {
    //   await deleteProduct(all[0].id);
    //   console.log(`🗑️ Produk ${all[0].nama_produk} berhasil dihapus`);
    // }
    // hapus semua produk
    // await deleteAllProducts();
    // console.log("🧹 Semua produk berhasil dihapus");
    // Cek hasi akhir
    // const final = await getAllProducts();
    // console.table(final);
}
seedProduk()
    .then(() => console.log("🌱 Selesai seeding"))
    .catch((err) => console.error("❌ Gagal seeding:", err));
