import { uploadProducts, getAllProducts, updateProduct, bulkUpdateProducts, deleteAllProducts, deleteProduct, } from "../lib/database.js";

import type { Product } from "../lib/database.js";

export async function seedProduk() {
  console.log("🚀 Menjalankan seed produk penuh...");

  // Bersihin dulu semua data biar isi baru
  // await deleteAllProducts();

  // Upload data produk baru
  const products: Product[] = [
    // KULINER
     {
    ASIN: "IDKUL001",
    nama_produk: "Sambal Cumi Asap Mak Rini",
    merek_produk: "Mak Rini",
    model_produk: "Sambal Rumahan 200g",
    kategori: "Kuliner",
    sub_kategori: "Sambal & Lauk Siap Saji",
    harga_asli: 45000,
    harga_produk: 35000,
    persentase_diskon: 22,
    mata_uang: "IDR",
    jumlah_unit: 500,
    unit_terjual: 430,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 200,
    bahan: "Cumi asap, cabai rawit, bawang merah, bawang putih, minyak kelapa",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Sambal cumi asap khas Jawa Timur dengan cita rasa pedas gurih dan aroma asap yang menggoda. Cocok disantap dengan nasi hangat atau lauk kering.",
    keyword: "sambal cumi pedas, kuliner nusantara",
    gambar_produk: "/img/kuliner/sambal-cumi.jpg",
    thumbnail_produk: "/img/kuliner/sambal-cumi-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/sambal-cumi1.jpg",
      "/img/kuliner/sambal-cumi2.jpg",
      "/img/kuliner/sambal-cumi3.jpg",
    ],
    toko: "Dapur Mak Rini",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Surabaya, Jawa Timur",
    rating_bintang: 4.9,
    jumlah_ulasan: 320,
  },

  {
    ASIN: "IDKUL002",
    nama_produk: "Keripik Pisang Cokelat Lampung",
    merek_produk: "BananaJoy",
    model_produk: "Snack 250g",
    kategori: "Kuliner",
    sub_kategori: "Camilan Tradisional",
    harga_asli: 28000,
    harga_produk: 22000,
    persentase_diskon: 21,
    mata_uang: "IDR",
    jumlah_unit: 800,
    unit_terjual: 620,
    status_produk: "Tersedia",
    minimum_pemesanan: 2,
    kondisi_produk: "Baru",
    berat_satuan: 250,
    bahan: "Pisang kepok, cokelat bubuk, gula, minyak kelapa",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Keripik pisang khas Lampung yang renyah dengan balutan cokelat premium. Snack manis yang cocok untuk oleh-oleh.",
    keyword: "keripik pisang, oleh-oleh lampung",
    gambar_produk: "/img/kuliner/keripik-pisang.jpg",
    thumbnail_produk: "/img/kuliner/keripik-pisang-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/keripik-pisang1.jpg",
      "/img/kuliner/keripik-pisang2.jpg",
      "/img/kuliner/keripik-pisang3.jpg",
    ],
    toko: "BananaJoy Official",
    rating_toko: 4.7,
    status_toko: "Official Store",
    lokasi_toko: "Bandar Lampung",
    rating_bintang: 4.8,
    jumlah_ulasan: 250,
  },

  {
    ASIN: "IDKUL003",
    nama_produk: "Rendang Padang Asli Daging Sapi 250g",
    merek_produk: "MinangRasa",
    model_produk: "Rendang Frozen 250g",
    kategori: "Kuliner",
    sub_kategori: "Lauk Siap Saji",
    harga_asli: 85000,
    harga_produk: 69000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 400,
    unit_terjual: 350,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 250,
    bahan: "Daging sapi, santan, cabai, bawang merah, bawang putih, rempah padang",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Rendang autentik khas Padang dengan bumbu meresap dan tekstur daging lembut. Tahan hingga 6 bulan dalam freezer.",
    keyword: "rendang padang, makanan frozen indonesia",
    gambar_produk: "/img/kuliner/rendang.jpg",
    thumbnail_produk: "/img/kuliner/rendang-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/rendang1.jpg",
      "/img/kuliner/rendang2.jpg",
      "/img/kuliner/rendang3.jpg",
    ],
    toko: "MinangRasa Store",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Padang, Sumatera Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 410,
  },

  {
    ASIN: "IDKUL004",
    nama_produk: "Kopi Arabika Gayo 200g",
    merek_produk: "GayoMount",
    model_produk: "Roasted Beans Medium",
    kategori: "Kuliner",
    sub_kategori: "Kopi & Minuman",
    harga_asli: 95000,
    harga_produk: 78000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 600,
    unit_terjual: 520,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 200,
    bahan: "Biji kopi arabika gayo 100%",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Kopi arabika premium dari dataran tinggi Gayo dengan cita rasa floral dan aftertaste cokelat lembut. Disangrai segar setiap minggu.",
    keyword: "kopi gayo arabika, kopi aceh",
    gambar_produk: "/img/kuliner/kopi-gayo.jpg",
    thumbnail_produk: "/img/kuliner/kopi-gayo-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/kopi-gayo1.jpg",
      "/img/kuliner/kopi-gayo2.jpg",
      "/img/kuliner/kopi-gayo3.jpg",
    ],
    toko: "GayoMount Coffee",
    rating_toko: 4.9,
    status_toko: "Toko Biasa",
    lokasi_toko: "Takengon, Aceh Tengah",
    rating_bintang: 4.8,
    jumlah_ulasan: 260,
  },

  {
    ASIN: "IDKUL005",
    nama_produk: "Dodol Garut Premium Rasa Durian",
    merek_produk: "DodolKita",
    model_produk: "Paket 500g",
    kategori: "Kuliner",
    sub_kategori: "Manisan & Oleh-oleh",
    harga_asli: 55000,
    harga_produk: 45000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 700,
    unit_terjual: 640,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 500,
    bahan: "Beras ketan, gula merah, santan, durian asli",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Dodol khas Garut dengan rasa durian legit dan aroma khas. Tekstur lembut dan tidak lengket di gigi.",
    keyword: "dodol garut, oleh oleh jawa barat",
    gambar_produk: "/img/kuliner/dodol-garut.jpg",
    thumbnail_produk: "/img/kuliner/dodol-garut-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/dodol-garut1.jpg",
      "/img/kuliner/dodol-garut2.jpg",
      "/img/kuliner/dodol-garut3.jpg",
    ],
    toko: "DodolKita Garut",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Garut, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 188,
  },

  {
    ASIN: "IDKUL006",
    nama_produk: "Nasi Liwet Instan Solo",
    merek_produk: "RasaJawa",
    model_produk: "Paket 300g",
    kategori: "Kuliner",
    sub_kategori: "Makanan Instan Tradisional",
    harga_asli: 60000,
    harga_produk: 48000,
    persentase_diskon: 20,
    mata_uang: "IDR",
    jumlah_unit: 500,
    unit_terjual: 450,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 300,
    bahan: "Beras, santan, bumbu khas solo, suwiran ayam, daun salam",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Nasi liwet khas Solo versi instan. Tinggal panaskan 5 menit, siap disajikan dengan aroma khas bumbu Jawa.",
    keyword: "nasi liwet solo, makanan instan tradisional",
    gambar_produk: "/img/kuliner/nasi-liwet.jpg",
    thumbnail_produk: "/img/kuliner/nasi-liwet-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/nasi-liwet1.jpg",
      "/img/kuliner/nasi-liwet2.jpg",
      "/img/kuliner/nasi-liwet3.jpg",
    ],
    toko: "RasaJawa Official",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Solo, Jawa Tengah",
    rating_bintang: 4.9,
    jumlah_ulasan: 233,
  },

  {
    ASIN: "IDKUL007",
    nama_produk: "Sate Maranggi Beku 10 Tusuk",
    merek_produk: "MaranggiMania",
    model_produk: "Frozen Pack 300g",
    kategori: "Kuliner",
    sub_kategori: "Lauk Beku",
    harga_asli: 75000,
    harga_produk: 62000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 400,
    unit_terjual: 350,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 300,
    bahan: "Daging sapi, kecap manis, bawang putih, jahe, ketumbar",
    deskripsi_produk:
      "Sate maranggi khas Purwakarta yang dibekukan segar. Siap panggang kapan pun dengan cita rasa otentik.",
    keyword: "sate maranggi, frozen food indonesia",
    gambar_produk: "/img/kuliner/sate-maranggi.jpg",
    thumbnail_produk: "/img/kuliner/sate-maranggi-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/sate-maranggi1.jpg",
      "/img/kuliner/sate-maranggi2.jpg",
      "/img/kuliner/sate-maranggi3.jpg",
    ],
    toko: "MaranggiMania",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Purwakarta, Jawa Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 312,
  },

  {
    ASIN: "IDKUL008",
    nama_produk: "Tempe Chips Crispy Original",
    merek_produk: "TempeQueen",
    model_produk: "Snack 150g",
    kategori: "Kuliner",
    sub_kategori: "Camilan Kering",
    harga_asli: 22000,
    harga_produk: 18000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 1000,
    unit_terjual: 880,
    status_produk: "Tersedia",
    minimum_pemesanan: 2,
    kondisi_produk: "Baru",
    berat_satuan: 150,
    bahan: "Tempe, tepung beras, garam, bumbu rempah",
    deskripsi_produk:
      "Keripik tempe super renyah tanpa MSG. Dibuat dari tempe kedelai pilihan dan minyak kelapa asli.",
    keyword: "keripik tempe, camilan sehat",
    gambar_produk: "/img/kuliner/keripik-tempe.jpg",
    thumbnail_produk: "/img/kuliner/keripik-tempe-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/keripik-tempe1.jpg",
      "/img/kuliner/keripik-tempe2.jpg",
      "/img/kuliner/keripik-tempe3.jpg",
    ],
    toko: "TempeQueen ID",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Malang, Jawa Timur",
    rating_bintang: 4.8,
    jumlah_ulasan: 280,
  },

  {
    ASIN: "IDKUL009",
    nama_produk: "Bumbu Pecel Madiun Kacang Asli",
    merek_produk: "PecelManten",
    model_produk: "Kemasan 250g",
    kategori: "Kuliner",
    sub_kategori: "Bumbu Tradisional",
    harga_asli: 32000,
    harga_produk: 26000,
    persentase_diskon: 19,
    mata_uang: "IDR",
    jumlah_unit: 400,
    unit_terjual: 340,
    status_produk: "Tersedia",
    minimum_pemesanan: 2,
    kondisi_produk: "Baru",
    berat_satuan: 250,
    bahan: "Kacang tanah, cabai, gula jawa, asam jawa, daun jeruk",
    deskripsi_produk:
      "Bumbu pecel khas Madiun, gurih pedas dan aromatik. Tinggal tambahkan air hangat dan siap disajikan.",
    keyword: "bumbu pecel madiun, kuliner jawa timur",
    gambar_produk: "/img/kuliner/bumbu-pecel.jpg",
    thumbnail_produk: "/img/kuliner/bumbu-pecel-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/bumbu-pecel1.jpg",
      "/img/kuliner/bumbu-pecel2.jpg",
      "/img/kuliner/bumbu-pecel3.jpg",
    ],
    toko: "PecelManten Store",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Madiun, Jawa Timur",
    rating_bintang: 4.9,
    jumlah_ulasan: 190,
  },

  {
    ASIN: "IDKUL010",
    nama_produk: "Sambal Roa Manado Asli 150g",
    merek_produk: "RoaMama",
    model_produk: "Sambal Ikan Roa",
    kategori: "Kuliner",
    sub_kategori: "Sambal Tradisional",
    harga_asli: 55000,
    harga_produk: 47000,
    persentase_diskon: 14,
    mata_uang: "IDR",
    jumlah_unit: 350,
    unit_terjual: 310,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 150,
    bahan: "Ikan roa asap, cabai merah, bawang putih, minyak kelapa",
    deskripsi_produk:
      "Sambal roa khas Manado dengan cita rasa pedas dan aroma asap ikan yang khas. Cocok untuk nasi, mie, atau roti panggang.",
    keyword: "sambal roa, kuliner manado",
    gambar_produk: "/img/kuliner/sambal-roa.jpg",
    thumbnail_produk: "/img/kuliner/sambal-roa-thumb.jpg",
    galeri_gambar: [
      "/img/kuliner/sambal-roa1.jpg",
      "/img/kuliner/sambal-roa2.jpg",
      "/img/kuliner/sambal-roa3.jpg",
    ],
    toko: "RoaMama Official",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Manado, Sulawesi Utara",
    rating_bintang: 4.9,
    jumlah_ulasan: 276,
  },

    // Jasa
  {
    ASIN: "IDJASA001",
    nama_produk: "Jasa Cuci Sepatu Profesional",
    merek_produk: "CleanStep",
    model_produk: "Deep Clean + Treatment",
    kategori: "Jasa",
    sub_kategori: "Perawatan Barang",
    harga_asli: 70000,
    harga_produk: 50000,
    persentase_diskon: 28,
    mata_uang: "IDR",
    jumlah_unit: 1000,
    unit_terjual: 820,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Layanan cuci sepatu profesional dengan metode deep clean, deodorizing, dan protection. Aman untuk bahan suede, kulit, dan knit.",
    keyword: "jasa cuci sepatu, perawatan alas kaki",
    gambar_produk: "/img/jasa/cuci-sepatu.jpg",
    thumbnail_produk: "/img/jasa/cuci-sepatu-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/cuci-sepatu1.jpg",
      "/img/jasa/cuci-sepatu2.jpg",
      "/img/jasa/cuci-sepatu3.jpg",
    ],
    toko: "CleanStep ID",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 210,
  },

  {
    ASIN: "IDJASA002",
    nama_produk: "Jasa Fotografi Produk UMKM",
    merek_produk: "Lensaku",
    model_produk: "Paket 20 Foto HD",
    kategori: "Jasa",
    sub_kategori: "Fotografi & Desain",
    harga_asli: 550000,
    harga_produk: 450000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 500,
    unit_terjual: 390,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Layanan foto produk profesional untuk UMKM. Termasuk styling, lighting, dan editing. Hasil siap upload ke marketplace.",
    keyword: "foto produk, jasa fotografi umkm",
    gambar_produk: "/img/jasa/foto-produk.jpg",
    thumbnail_produk: "/img/jasa/foto-produk-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/foto-produk1.jpg",
      "/img/jasa/foto-produk2.jpg",
      "/img/jasa/foto-produk3.jpg",
    ],
    toko: "Lensaku Studio",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.9,
    jumlah_ulasan: 330,
  },

  {
    ASIN: "IDJASA003",
    nama_produk: "Jasa Potong Rambut & Styling Pria",
    merek_produk: "BarberCraft",
    model_produk: "Classic + Fade",
    kategori: "Jasa",
    sub_kategori: "Grooming & Perawatan Diri",
    harga_asli: 60000,
    harga_produk: 45000,
    persentase_diskon: 25,
    mata_uang: "IDR",
    jumlah_unit: 1000,
    unit_terjual: 870,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Layanan potong rambut profesional dengan barber berpengalaman. Termasuk cuci rambut, pomade styling, dan pijat kepala.",
    keyword: "barber pria, potong rambut jakarta",
    gambar_produk: "/img/jasa/barber.jpg",
    thumbnail_produk: "/img/jasa/barber-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/barber1.jpg",
      "/img/jasa/barber2.jpg",
      "/img/jasa/barber3.jpg",
    ],
    toko: "BarberCraft Studio",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Jakarta Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 540,
  },

  {
    ASIN: "IDJASA004",
    nama_produk: "Jasa Desain Logo Bisnis",
    merek_produk: "BrandLab",
    model_produk: "Logo Starter Pack",
    kategori: "Jasa",
    sub_kategori: "Desain Grafis",
    harga_asli: 350000,
    harga_produk: 290000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 9999,
    unit_terjual: 3200,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Desain logo profesional untuk bisnis kecil dan startup. Termasuk 3 konsep awal dan 2 revisi. File final dalam format AI, PNG, JPG.",
    keyword: "desain logo profesional, jasa desain indonesia",
    gambar_produk: "/img/jasa/desain-logo.jpg",
    thumbnail_produk: "/img/jasa/desain-logo-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/desain-logo1.jpg",
      "/img/jasa/desain-logo2.jpg",
      "/img/jasa/desain-logo3.jpg",
    ],
    toko: "BrandLab Creative",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Surabaya, Jawa Timur",
    rating_bintang: 4.9,
    jumlah_ulasan: 280,
  },

  {
    ASIN: "IDJASA005",
    nama_produk: "Servis Laptop & Komputer Rumah",
    merek_produk: "TeknoFix",
    model_produk: "Home Service",
    kategori: "Jasa",
    sub_kategori: "Teknologi & Elektronik",
    harga_asli: 200000,
    harga_produk: 150000,
    persentase_diskon: 25,
    mata_uang: "IDR",
    jumlah_unit: 200,
    unit_terjual: 160,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Layanan servis laptop dan PC di rumah. Bisa panggilan untuk instalasi software, ganti thermal paste, atau troubleshooting sistem.",
    keyword: "servis laptop panggilan, teknisi komputer",
    gambar_produk: "/img/jasa/servis-laptop.jpg",
    thumbnail_produk: "/img/jasa/servis-laptop-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/servis-laptop1.jpg",
      "/img/jasa/servis-laptop2.jpg",
      "/img/jasa/servis-laptop3.jpg",
    ],
    toko: "TeknoFix Indonesia",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Depok, Jawa Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 212,
  },

  {
    ASIN: "IDJASA006",
    nama_produk: "Jasa Pembersihan Rumah & Apartemen",
    merek_produk: "CleanHouse ID",
    model_produk: "Full Cleaning 3 Jam",
    kategori: "Jasa",
    sub_kategori: "Kebersihan & Rumah Tangga",
    harga_asli: 250000,
    harga_produk: 190000,
    persentase_diskon: 24,
    mata_uang: "IDR",
    jumlah_unit: 600,
    unit_terjual: 510,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Jasa bersih-bersih rumah profesional. Termasuk vakum karpet, dapur, kamar mandi, dan area umum. Peralatan lengkap dari kami.",
    keyword: "jasa bersih rumah, cleaning service panggilan",
    gambar_produk: "/img/jasa/cleaning-service.jpg",
    thumbnail_produk: "/img/jasa/cleaning-service-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/cleaning-service1.jpg",
      "/img/jasa/cleaning-service2.jpg",
      "/img/jasa/cleaning-service3.jpg",
    ],
    toko: "CleanHouse ID",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.9,
    jumlah_ulasan: 415,
  },

  {
    ASIN: "IDJASA007",
    nama_produk: "Jasa Pengiriman Barang Motor",
    merek_produk: "GoKirim",
    model_produk: "Express Delivery",
    kategori: "Jasa",
    sub_kategori: "Pengiriman & Logistik",
    harga_asli: 30000,
    harga_produk: 25000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 5000,
    unit_terjual: 4500,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Layanan pengiriman cepat dalam kota menggunakan motor. Aman, cepat, dan bisa tracking langsung.",
    keyword: "kurir motor, jasa kirim cepat",
    gambar_produk: "/img/jasa/pengiriman.jpg",
    thumbnail_produk: "/img/jasa/pengiriman-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/pengiriman1.jpg",
      "/img/jasa/pengiriman2.jpg",
      "/img/jasa/pengiriman3.jpg",
    ],
    toko: "GoKirim Express",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Timur",
    rating_bintang: 4.9,
    jumlah_ulasan: 390,
  },

  {
    ASIN: "IDJASA008",
    nama_produk: "Jasa Les Privat SD-SMP",
    merek_produk: "CerdasHome",
    model_produk: "Guru Datang ke Rumah",
    kategori: "Jasa",
    sub_kategori: "Pendidikan & Bimbingan",
    harga_asli: 150000,
    harga_produk: 120000,
    persentase_diskon: 20,
    mata_uang: "IDR",
    jumlah_unit: 300,
    unit_terjual: 270,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Layanan les privat untuk jenjang SD–SMP. Guru berpengalaman datang langsung ke rumah. Bisa pilih mata pelajaran dan jadwal fleksibel.",
    keyword: "les privat sd smp, guru datang ke rumah",
    gambar_produk: "/img/jasa/les-privat.jpg",
    thumbnail_produk: "/img/jasa/les-privat-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/les-privat1.jpg",
      "/img/jasa/les-privat2.jpg",
      "/img/jasa/les-privat3.jpg",
    ],
    toko: "CerdasHome ID",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Tangerang Selatan",
    rating_bintang: 4.9,
    jumlah_ulasan: 265,
  },

  {
    ASIN: "IDJASA009",
    nama_produk: "Jasa Servis AC Panggilan",
    merek_produk: "CoolFix",
    model_produk: "Cuci + Freon",
    kategori: "Jasa",
    sub_kategori: "Perawatan Elektronik",
    harga_asli: 200000,
    harga_produk: 160000,
    persentase_diskon: 20,
    mata_uang: "IDR",
    jumlah_unit: 700,
    unit_terjual: 610,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Jasa cuci dan isi freon AC panggilan ke rumah. Teknisi berpengalaman dan bergaransi 7 hari.",
    keyword: "servis ac panggilan, cuci ac rumah",
    gambar_produk: "/img/jasa/servis-ac.jpg",
    thumbnail_produk: "/img/jasa/servis-ac-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/servis-ac1.jpg",
      "/img/jasa/servis-ac2.jpg",
      "/img/jasa/servis-ac3.jpg",
    ],
    toko: "CoolFix Service",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Bekasi, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 180,
  },

  {
    ASIN: "IDJASA010",
    nama_produk: "Jasa Makeup & Hairdo Wisuda",
    merek_produk: "Glamify",
    model_produk: "Natural Look Paket",
    kategori: "Jasa",
    sub_kategori: "Kecantikan & Event",
    harga_asli: 400000,
    harga_produk: 330000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 500,
    unit_terjual: 410,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Jasa makeup wisuda natural oleh MUA profesional. Termasuk hairdo, soft lens, dan setting spray tahan lama.",
    keyword: "jasa makeup wisuda, mua panggilan",
    gambar_produk: "/img/jasa/makeup.jpg",
    thumbnail_produk: "/img/jasa/makeup-thumb.jpg",
    galeri_gambar: [
      "/img/jasa/makeup1.jpg",
      "/img/jasa/makeup2.jpg",
      "/img/jasa/makeup3.jpg",
    ],
    toko: "Glamify Studio",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Yogyakarta",
    rating_bintang: 4.9,
    jumlah_ulasan: 295,
  },

    // KESEHATAN
  {
    ASIN: "IDHEALTH001",
    nama_produk: "Vitamin C 1000mg - Suplemen Daya Tahan Tubuh",
    merek_produk: "Wellness ID",
    model_produk: "Botol 30 Tablet",
    kategori: "Kesehatan",
    sub_kategori: "Suplemen & Vitamin",
    harga_asli: 95000,
    harga_produk: 75000,
    persentase_diskon: 21,
    mata_uang: "IDR",
    jumlah_unit: 500,
    unit_terjual: 410,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 200,
    bahan: "Vitamin C, Zinc, Citrus Extract",
    deskripsi_produk:
      "Suplemen Vitamin C 1000mg untuk menjaga daya tahan tubuh, membantu pembentukan kolagen, dan meningkatkan energi harian.",
    keyword: "vitamin c, daya tahan tubuh, suplemen kesehatan",
    gambar_produk: "/img/kesehatan/vitamin-c.jpg",
    thumbnail_produk: "/img/kesehatan/vitamin-c-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/vitamin-c1.jpg",
      "/img/kesehatan/vitamin-c2.jpg",
      "/img/kesehatan/vitamin-c3.jpg",
    ],
    toko: "Wellness Official",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.9,
    jumlah_ulasan: 230,
  },

  {
    ASIN: "IDHEALTH002",
    nama_produk: "Masker KF94 Medis 4 Ply",
    merek_produk: "Airmed",
    model_produk: "Pack isi 10",
    kategori: "Kesehatan",
    sub_kategori: "Perlengkapan Medis",
    harga_asli: 40000,
    harga_produk: 30000,
    persentase_diskon: 25,
    mata_uang: "IDR",
    jumlah_unit: 2000,
    unit_terjual: 1750,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 100,
    bahan: "Non-woven Fabric 4 Ply",
    deskripsi_produk:
      "Masker medis 4 lapis (KF94) dengan filter electrostatic yang melindungi dari debu, bakteri, dan virus hingga 94%.",
    keyword: "masker medis, kf94 indonesia, perlengkapan kesehatan",
    gambar_produk: "/img/kesehatan/masker-kf94.jpg",
    thumbnail_produk: "/img/kesehatan/masker-kf94-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/masker-kf94-1.jpg",
      "/img/kesehatan/masker-kf94-2.jpg",
      "/img/kesehatan/masker-kf94-3.jpg",
    ],
    toko: "Airmed Official",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Tangerang, Banten",
    rating_bintang: 4.9,
    jumlah_ulasan: 320,
  },

  {
    ASIN: "IDHEALTH003",
    nama_produk: "Minyak Eukaliptus Aromaterapi",
    merek_produk: "Cap Lang",
    model_produk: "Botol 30ml",
    kategori: "Kesehatan",
    sub_kategori: "Minyak & Aromaterapi",
    harga_asli: 25000,
    harga_produk: 19000,
    persentase_diskon: 24,
    mata_uang: "IDR",
    jumlah_unit: 1500,
    unit_terjual: 1200,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 80,
    bahan: "Eucalyptus Oil, Menthol, Camphor",
    deskripsi_produk:
      "Minyak eukaliptus serbaguna dengan aroma menyegarkan. Efektif meredakan pegal, hidung tersumbat, dan memberikan relaksasi alami.",
    keyword: "minyak kayu putih, aromaterapi, eukaliptus",
    gambar_produk: "/img/kesehatan/minyak-eukaliptus.jpg",
    thumbnail_produk: "/img/kesehatan/minyak-eukaliptus-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/minyak-eukaliptus1.jpg",
      "/img/kesehatan/minyak-eukaliptus2.jpg",
      "/img/kesehatan/minyak-eukaliptus3.jpg",
    ],
    toko: "Cap Lang Indonesia",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 410,
  },

  {
    ASIN: "IDHEALTH004",
    nama_produk: "Termometer Digital Infrared Non Contact",
    merek_produk: "MediCheck",
    model_produk: "MC-102",
    kategori: "Kesehatan",
    sub_kategori: "Alat Medis Elektronik",
    harga_asli: 300000,
    harga_produk: 230000,
    persentase_diskon: 23,
    mata_uang: "IDR",
    jumlah_unit: 400,
    unit_terjual: 340,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 250,
    deskripsi_produk:
      "Termometer digital infrared yang akurat, cepat, dan higienis tanpa perlu kontak langsung. Ideal untuk anak dan dewasa.",
    keyword: "termometer digital, alat cek suhu",
    gambar_produk: "/img/kesehatan/termometer.jpg",
    thumbnail_produk: "/img/kesehatan/termometer-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/termometer1.jpg",
      "/img/kesehatan/termometer2.jpg",
      "/img/kesehatan/termometer3.jpg",
    ],
    toko: "MediCheck ID",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Surabaya, Jawa Timur",
    rating_bintang: 4.8,
    jumlah_ulasan: 180,
  },

  {
    ASIN: "IDHEALTH005",
    nama_produk: "Obat Herbal Asam Lambung",
    merek_produk: "TogaNusantara",
    model_produk: "Kapsul 60 Butir",
    kategori: "Kesehatan",
    sub_kategori: "Obat Herbal",
    harga_asli: 85000,
    harga_produk: 69000,
    persentase_diskon: 19,
    mata_uang: "IDR",
    jumlah_unit: 600,
    unit_terjual: 520,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 120,
    bahan: "Temulawak, Kunyit, Daun Jinten",
    deskripsi_produk:
      "Kapsul herbal alami membantu meredakan asam lambung, nyeri ulu hati, dan mual tanpa efek samping bahan kimia.",
    keyword: "obat herbal, asam lambung, jamu tradisional",
    gambar_produk: "/img/kesehatan/obat-herbal.jpg",
    thumbnail_produk: "/img/kesehatan/obat-herbal-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/obat-herbal1.jpg",
      "/img/kesehatan/obat-herbal2.jpg",
      "/img/kesehatan/obat-herbal3.jpg",
    ],
    toko: "TogaNusantara",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Yogyakarta",
    rating_bintang: 4.9,
    jumlah_ulasan: 290,
  },

  {
    ASIN: "IDHEALTH006",
    nama_produk: "Essential Oil Peppermint",
    merek_produk: "Aromaku",
    model_produk: "Botol 10ml",
    kategori: "Kesehatan",
    sub_kategori: "Aromaterapi",
    harga_asli: 80000,
    harga_produk: 62000,
    persentase_diskon: 22,
    mata_uang: "IDR",
    jumlah_unit: 800,
    unit_terjual: 640,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 60,
    bahan: "Minyak Peppermint Murni",
    deskripsi_produk:
      "Minyak esensial peppermint untuk relaksasi, meredakan sakit kepala, dan meningkatkan konsentrasi. 100% pure essential oil.",
    keyword: "essential oil, aromaterapi peppermint",
    gambar_produk: "/img/kesehatan/essential-oil.jpg",
    thumbnail_produk: "/img/kesehatan/essential-oil-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/essential-oil1.jpg",
      "/img/kesehatan/essential-oil2.jpg",
      "/img/kesehatan/essential-oil3.jpg",
    ],
    toko: "Aromaku ID",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Bali",
    rating_bintang: 4.9,
    jumlah_ulasan: 315,
  },

  {
    ASIN: "IDHEALTH007",
    nama_produk: "Alat Pijat Elektrik Leher & Pundak",
    merek_produk: "RelaxPro",
    model_produk: "Neck Massager 360",
    kategori: "Kesehatan",
    sub_kategori: "Perawatan Tubuh",
    harga_asli: 480000,
    harga_produk: 375000,
    persentase_diskon: 22,
    mata_uang: "IDR",
    jumlah_unit: 300,
    unit_terjual: 250,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 850,
    deskripsi_produk:
      "Alat pijat elektrik dengan fungsi pemanas untuk meredakan nyeri leher dan pundak. Dilengkapi mode getar dan infrared therapy.",
    keyword: "alat pijat elektrik, neck massager",
    gambar_produk: "/img/kesehatan/alat-pijat.jpg",
    thumbnail_produk: "/img/kesehatan/alat-pijat-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/alat-pijat1.jpg",
      "/img/kesehatan/alat-pijat2.jpg",
      "/img/kesehatan/alat-pijat3.jpg",
    ],
    toko: "RelaxPro Indonesia",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 190,
  },

  {
    ASIN: "IDHEALTH008",
    nama_produk: "Hand Sanitizer Aloe Vera 250ml",
    merek_produk: "BioCare",
    model_produk: "Botol Pump",
    kategori: "Kesehatan",
    sub_kategori: "Perawatan Diri",
    harga_asli: 28000,
    harga_produk: 20000,
    persentase_diskon: 29,
    mata_uang: "IDR",
    jumlah_unit: 2000,
    unit_terjual: 1800,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 300,
    bahan: "Ethanol 70%, Aloe Vera Extract",
    deskripsi_produk:
      "Hand sanitizer dengan kandungan aloe vera yang melembapkan tangan. Efektif membunuh 99.9% kuman tanpa membuat kulit kering.",
    keyword: "hand sanitizer aloe vera, cairan antiseptik",
    gambar_produk: "/img/kesehatan/hand-sanitizer.jpg",
    thumbnail_produk: "/img/kesehatan/hand-sanitizer-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/hand-sanitizer1.jpg",
      "/img/kesehatan/hand-sanitizer2.jpg",
      "/img/kesehatan/hand-sanitizer3.jpg",
    ],
    toko: "BioCare Store",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Depok, Jawa Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 410,
  },

  {
    ASIN: "IDHEALTH009",
    nama_produk: "Timbangan Badan Digital SmartScale",
    merek_produk: "FitTrack",
    model_produk: "Bluetooth BMI Monitor",
    kategori: "Kesehatan",
    sub_kategori: "Smart Health Device",
    harga_asli: 490000,
    harga_produk: 399000,
    persentase_diskon: 19,
    mata_uang: "IDR",
    jumlah_unit: 400,
    unit_terjual: 310,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 1200,
    deskripsi_produk:
      "Timbangan digital pintar dengan koneksi Bluetooth untuk memantau berat badan, BMI, dan komposisi tubuh langsung di aplikasi HP.",
    keyword: "smart scale, timbangan digital",
    gambar_produk: "/img/kesehatan/smart-scale.jpg",
    thumbnail_produk: "/img/kesehatan/smart-scale-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/smart-scale1.jpg",
      "/img/kesehatan/smart-scale2.jpg",
      "/img/kesehatan/smart-scale3.jpg",
    ],
    toko: "FitTrack Indonesia",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Pusat",
    rating_bintang: 4.9,
    jumlah_ulasan: 280,
  },

  {
    ASIN: "IDHEALTH010",
    nama_produk: "Teh Herbal Detoks Tubuh",
    merek_produk: "DaunSehat",
    model_produk: "Kemasan 20 Sachet",
    kategori: "Kesehatan",
    sub_kategori: "Herbal & Minuman Sehat",
    harga_asli: 65000,
    harga_produk: 52000,
    persentase_diskon: 20,
    mata_uang: "IDR",
    jumlah_unit: 900,
    unit_terjual: 720,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 180,
    bahan: "Daun jati cina, jahe, serai, madu alami",
    deskripsi_produk:
      "Teh herbal alami untuk membantu proses detoksifikasi tubuh, melancarkan pencernaan, dan menjaga berat badan ideal.",
    keyword: "teh herbal detoks, minuman sehat alami",
    gambar_produk: "/img/kesehatan/teh-herbal.jpg",
    thumbnail_produk: "/img/kesehatan/teh-herbal-thumb.jpg",
    galeri_gambar: [
      "/img/kesehatan/teh-herbal1.jpg",
      "/img/kesehatan/teh-herbal2.jpg",
      "/img/kesehatan/teh-herbal3.jpg",
    ],
    toko: "DaunSehat ID",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Bogor, Jawa Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 350,
  },

    // Fashion
  {
    ASIN: "FASH-001",
    nama_produk: "Batik Tulis Pekalongan Pria Lengan Panjang",
    merek_produk: "Batik Nusantara",
    model_produk: "Kemeja Batik Pria Formal",
    kategori: "Fashion",
    sub_kategori: "Batik",
    harga_asli: 450000,
    harga_produk: 299000,
    persentase_diskon: 33,
    mata_uang: "IDR",
    jumlah_unit: 50,
    unit_terjual: 120,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.5,
    bahan: "Katun Primisima",
    warna: "Coklat Motif Klasik",
    negara_asal: "Indonesia",
    spesifikasi: "Batik tulis asli Pekalongan dengan pewarna alami.",
    deskripsi_produk:
      "Kemeja batik tulis khas Pekalongan ini dibuat secara manual oleh pengrajin berpengalaman. Nyaman dipakai dan cocok untuk acara formal maupun santai.",
    keyword: "batik pekalongan, kemeja batik pria",
    gambar_produk: "/asset/fashion/batik1.jpg",
    thumbnail_produk: "/asset/fashion/batik1a.jpg",
    galeri_gambar: [
      "/asset/fashion/batik1a.jpg",
      "/asset/fashion/batik1b.jpg",
      "/asset/fashion/batik1c.jpg",
    ],
    toko: "Batik Asli Nusantara",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Pekalongan, Jawa Tengah",
    rating_bintang: 4.8,
    jumlah_ulasan: 324,
  },
  {
    ASIN: "FASH-002",
    nama_produk: "Kebaya Encim Modern",
    merek_produk: "Pesona Kartini",
    model_produk: "Kebaya Bordir",
    kategori: "Fashion",
    sub_kategori: "Kebaya",
    harga_asli: 600000,
    harga_produk: 450000,
    persentase_diskon: 25,
    mata_uang: "IDR",
    jumlah_unit: 30,
    unit_terjual: 85,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.7,
    bahan: "Brokat Halus",
    warna: "Merah Marun",
    negara_asal: "Indonesia",
    spesifikasi: "Kebaya encim dengan sentuhan modern dan bordir halus.",
    deskripsi_produk:
      "Kebaya modern dengan desain klasik khas Betawi. Cocok untuk acara resmi, wisuda, atau pernikahan.",
    keyword: "kebaya encim, kebaya modern",
    gambar_produk: "/asset/fashion/kebaya1.jpg",
    thumbnail_produk: "/asset/fashion/kebaya1a.jpg",
    galeri_gambar: [
      "/asset/fashion/kebaya1a.jpg",
      "/asset/fashion/kebaya1b.jpg",
      "/asset/fashion/kebaya1c.jpg",
    ],
    toko: "Pesona Kartini",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Jakarta Pusat",
    rating_bintang: 4.6,
    jumlah_ulasan: 215,
  },
  {
    ASIN: "FASH-003",
    nama_produk: "Sepatu Kulit Asli Handmade Bandung",
    merek_produk: "D'Leather",
    model_produk: "Oxford Shoes",
    kategori: "Fashion",
    sub_kategori: "Sepatu",
    harga_asli: 850000,
    harga_produk: 599000,
    persentase_diskon: 30,
    mata_uang: "IDR",
    jumlah_unit: 40,
    unit_terjual: 210,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 1.2,
    bahan: "Kulit Sapi Premium",
    warna: "Coklat Tua",
    negara_asal: "Indonesia",
    spesifikasi: "Jahitan rapi, sol kuat, dan tahan lama.",
    deskripsi_produk:
      "Sepatu kulit handmade buatan Bandung, cocok untuk kegiatan formal maupun kasual. Nyaman dipakai seharian.",
    keyword: "sepatu kulit bandung, handmade shoes",
    gambar_produk: "/asset/fashion/sepatu1.jpg",
    thumbnail_produk: "/asset/fashion/sepatu1a.jpg",
    galeri_gambar: [
      "/asset/fashion/sepatu1a.jpg",
      "/asset/fashion/sepatu1b.jpg",
      "/asset/fashion/sepatu1c.jpg",
    ],
    toko: "D'Leather Craft",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.7,
    jumlah_ulasan: 432,
  },
  {
    ASIN: "FASH-004",
    nama_produk: "Tas Anyaman Pandan Khas Bali",
    merek_produk: "TropicaBag",
    model_produk: "Tas Selempang Wanita",
    kategori: "Fashion",
    sub_kategori: "Aksesoris",
    harga_asli: 250000,
    harga_produk: 175000,
    persentase_diskon: 30,
    mata_uang: "IDR",
    jumlah_unit: 60,
    unit_terjual: 300,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.4,
    bahan: "Daun Pandan Kering",
    warna: "Natural Cream",
    negara_asal: "Indonesia",
    spesifikasi: "Produk handmade ramah lingkungan dari Bali.",
    deskripsi_produk:
      "Tas anyaman pandan dibuat oleh pengrajin lokal Bali. Ringan, kuat, dan cocok untuk gaya kasual atau pantai.",
    keyword: "tas pandan bali, tas anyaman alami",
    gambar_produk: "/asset/fashion/tas1.jpg",
    thumbnail_produk: "/asset/fashion/tas1a.jpg",
    galeri_gambar: [
      "/asset/fashion/tas1a.jpg",
      "/asset/fashion/tas1b.jpg",
      "/asset/fashion/tas1c.jpg",
    ],
    toko: "Bali Craft House",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Denpasar, Bali",
    rating_bintang: 4.8,
    jumlah_ulasan: 368,
  },
  {
    ASIN: "FASH-005",
    nama_produk: "Jakarta Streetwear Hoodie",
    merek_produk: "Urban.id",
    model_produk: "Hoodie Oversize",
    kategori: "Fashion",
    sub_kategori: "Pakaian Kasual",
    harga_asli: 350000,
    harga_produk: 249000,
    persentase_diskon: 29,
    mata_uang: "IDR",
    jumlah_unit: 80,
    unit_terjual: 540,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.9,
    bahan: "Fleece Cotton",
    warna: "Hitam",
    negara_asal: "Indonesia",
    spesifikasi: "Desain khas urban Jakarta, sablon awet dan adem.",
    deskripsi_produk:
      "Hoodie bergaya streetwear dengan logo khas Jakarta. Nyaman dipakai dan cocok untuk aktivitas sehari-hari.",
    keyword: "jakarta hoodie, streetwear indonesia",
    gambar_produk: "/asset/fashion/hoodie1.jpg",
    thumbnail_produk: "/asset/fashion/hoodie1a.jpg",
    galeri_gambar: [
      "/asset/fashion/hoodie1a.jpg",
      "/asset/fashion/hoodie1b.jpg",
      "/asset/fashion/hoodie1c.jpg",
    ],
    toko: "Urban.id Apparel",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.7,
    jumlah_ulasan: 502,
  },
  {
    ASIN: "FASH-006",
    nama_produk: "Topi Tenun Troso Unisex",
    merek_produk: "Lurik.ID",
    model_produk: "Topi Casual",
    kategori: "Fashion",
    sub_kategori: "Aksesoris",
    harga_asli: 180000,
    harga_produk: 120000,
    persentase_diskon: 33,
    mata_uang: "IDR",
    jumlah_unit: 100,
    unit_terjual: 290,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.2,
    bahan: "Tenun Troso Jepara",
    warna: "Abu-abu Polos",
    negara_asal: "Indonesia",
    spesifikasi: "Topi handmade dengan kain tradisional Troso.",
    deskripsi_produk:
      "Topi unisex dengan bahan tenun Troso yang lembut dan adem, cocok untuk aktivitas outdoor.",
    keyword: "topi tenun, aksesoris handmade",
    gambar_produk: "/asset/fashion/topi1.jpg",
    thumbnail_produk: "/asset/fashion/topi1a.jpg",
    galeri_gambar: [
      "/asset/fashion/topi1a.jpg",
      "/asset/fashion/topi1b.jpg",
      "/asset/fashion/topi1c.jpg",
    ],
    toko: "Lurik.ID",
    rating_toko: 4.6,
    status_toko: "Toko Biasa",
    lokasi_toko: "Jepara, Jawa Tengah",
    rating_bintang: 4.5,
    jumlah_ulasan: 143,
  },
  {
    ASIN: "FASH-007",
    nama_produk: "Hijab Voal Premium",
    merek_produk: "Zahra Scarf",
    model_produk: "Segi Empat",
    kategori: "Fashion",
    sub_kategori: "Hijab",
    harga_asli: 120000,
    harga_produk: 85000,
    persentase_diskon: 29,
    mata_uang: "IDR",
    jumlah_unit: 150,
    unit_terjual: 670,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.25,
    bahan: "Voal Premium",
    warna: "Sage Green",
    negara_asal: "Indonesia",
    spesifikasi: "Lembut, tidak licin, dan mudah dibentuk.",
    deskripsi_produk:
      "Hijab segi empat dari bahan voal premium yang adem dan tidak menerawang. Warna soft cocok untuk berbagai outfit.",
    keyword: "hijab voal, jilbab premium",
    gambar_produk: "/asset/fashion/hijab1.jpg",
    thumbnail_produk: "/asset/fashion/hijab1a.jpg",
    galeri_gambar: [
      "/asset/fashion/hijab1a.jpg",
      "/asset/fashion/hijab1b.jpg",
      "/asset/fashion/hijab1c.jpg",
    ],
    toko: "Zahra Scarf Official",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Depok, Jawa Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 789,
  },
  {
    ASIN: "FASH-008",
    nama_produk: "Sandal Kulit Etnik Lombok",
    merek_produk: "SasakWalk",
    model_produk: "Sandal Pria",
    kategori: "Fashion",
    sub_kategori: "Sandal",
    harga_asli: 230000,
    harga_produk: 165000,
    persentase_diskon: 28,
    mata_uang: "IDR",
    jumlah_unit: 70,
    unit_terjual: 220,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.8,
    bahan: "Kulit Domba",
    warna: "Coklat Alam",
    negara_asal: "Indonesia",
    spesifikasi: "Tali anyaman khas Lombok, sol empuk.",
    deskripsi_produk:
      "Sandal etnik buatan tangan dari Lombok dengan bahan kulit berkualitas dan desain khas budaya Sasak.",
    keyword: "sandal etnik lombok, sandal kulit",
    gambar_produk: "/asset/fashion/sandal1.jpg",
    thumbnail_produk: "/asset/fashion/sandal1a.jpg",
    galeri_gambar: [
      "/asset/fashion/sandal1a.jpg",
      "/asset/fashion/sandal1b.jpg",
      "/asset/fashion/sandal1c.jpg",
    ],
    toko: "SasakWalk",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Lombok, NTB",
    rating_bintang: 4.6,
    jumlah_ulasan: 196,
  },
  {
    ASIN: "FASH-009",
    nama_produk: "Ransel Kanvas Retro",
    merek_produk: "JunglePack",
    model_produk: "Backpack Unisex",
    kategori: "Fashion",
    sub_kategori: "Tas",
    harga_asli: 320000,
    harga_produk: 235000,
    persentase_diskon: 26,
    mata_uang: "IDR",
    jumlah_unit: 90,
    unit_terjual: 510,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 1.1,
    bahan: "Kanvas Tebal",
    warna: "Army Green",
    negara_asal: "Indonesia",
    spesifikasi: "Anti air ringan, banyak kompartemen.",
    deskripsi_produk:
      "Ransel kanvas bergaya retro untuk kegiatan harian, kuliah, atau jalan-jalan. Tahan lama dan stylish.",
    keyword: "ransel kanvas, tas retro indonesia",
    gambar_produk: "/asset/fashion/ransel1.jpg",
    thumbnail_produk: "/asset/fashion/ransel1a.jpg",
    galeri_gambar: [
      "/asset/fashion/ransel1a.jpg",
      "/asset/fashion/ransel1b.jpg",
      "/asset/fashion/ransel1c.jpg",
    ],
    toko: "JunglePack Gear",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Malang, Jawa Timur",
    rating_bintang: 4.7,
    jumlah_ulasan: 401,
  },
  {
    ASIN: "FASH-010",
    nama_produk: "Outer Rajut Wanita Premium",
    merek_produk: "Knitt.ID",
    model_produk: "Cardigan Rajut",
    kategori: "Fashion",
    sub_kategori: "Outerwear",
    harga_asli: 270000,
    harga_produk: 189000,
    persentase_diskon: 30,
    mata_uang: "IDR",
    jumlah_unit: 85,
    unit_terjual: 430,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.7,
    bahan: "Benang Acrylic Lembut",
    warna: "Beige",
    negara_asal: "Indonesia",
    spesifikasi: "Rajutan rapi dan lentur, cocok untuk semua musim.",
    deskripsi_produk:
      "Outer rajut stylish dan lembut buatan lokal. Desain simple cocok dipadukan dengan outfit formal maupun santai.",
    keyword: "outer rajut, cardigan wanita lokal",
    gambar_produk: "/asset/fashion/outer1.jpg",
    thumbnail_produk: "/asset/fashion/outer1a.jpg",
    galeri_gambar: [
      "/asset/fashion/outer1a.jpg",
      "/asset/fashion/outer1b.jpg",
      "/asset/fashion/outer1c.jpg",
    ],
    toko: "Knitt.ID",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 382,
  },

    // PERTANIAN
  {
    ASIN: "AGRI-001",
    nama_produk: "Pupuk Organik Cair Biotan",
    merek_produk: "AgroNusa",
    model_produk: "POC Bio-Formula",
    kategori: "Pertanian",
    sub_kategori: "Pupuk",
    harga_asli: 80000,
    harga_produk: 59000,
    persentase_diskon: 26,
    mata_uang: "IDR",
    jumlah_unit: 200,
    unit_terjual: 650,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 1,
    dimensi_produk: "25x10x10 cm",
    bahan: "Ekstrak mikroba dan bahan organik alami",
    negara_asal: "Indonesia",
    spesifikasi: "Cocok untuk padi, sayuran, dan tanaman buah.",
    deskripsi_produk:
      "Pupuk organik cair Biotan membantu meningkatkan kesuburan tanah dan mempercepat pertumbuhan tanaman secara alami tanpa bahan kimia.",
    keyword: "pupuk organik cair, pertanian organik",
    gambar_produk: "/asset/pertanian/pupuk1.jpg",
    thumbnail_produk: "/asset/pertanian/pupuk1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/pupuk1a.jpg",
      "/asset/pertanian/pupuk1b.jpg",
      "/asset/pertanian/pupuk1c.jpg",
    ],
    toko: "Tani Jaya Abadi",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Bogor, Jawa Barat",
    rating_bintang: 4.7,
    jumlah_ulasan: 512,
  },
  {
    ASIN: "AGRI-002",
    nama_produk: "Benih Padi Ciherang Unggul",
    merek_produk: "TaniMakmur",
    model_produk: "Benih Padi IR-64",
    kategori: "Pertanian",
    sub_kategori: "Benih",
    harga_asli: 65000,
    harga_produk: 49000,
    persentase_diskon: 25,
    mata_uang: "IDR",
    jumlah_unit: 300,
    unit_terjual: 780,
    status_produk: "Tersedia",
    minimum_pemesanan: 2,
    kondisi_produk: "Baru",
    berat_satuan: 5,
    negara_asal: "Indonesia",
    spesifikasi: "Bersertifikat, daya tumbuh 95%.",
    deskripsi_produk:
      "Benih padi Ciherang unggul cocok untuk berbagai jenis lahan, memiliki ketahanan terhadap hama wereng dan hasil panen tinggi.",
    keyword: "benih padi unggul, padi ciherang",
    gambar_produk: "/asset/pertanian/benih1.jpg",
    thumbnail_produk: "/asset/pertanian/benih1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/benih1a.jpg",
      "/asset/pertanian/benih1b.jpg",
      "/asset/pertanian/benih1c.jpg",
    ],
    toko: "UD TaniMakmur",
    rating_toko: 4.9,
    status_toko: "Toko Biasa",
    lokasi_toko: "Subang, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 368,
  },
  {
    ASIN: "AGRI-003",
    nama_produk: "Sprayer Elektrik 16L",
    merek_produk: "AgriTech",
    model_produk: "Sprayer AG16E",
    kategori: "Pertanian",
    sub_kategori: "Alat Pertanian",
    harga_asli: 650000,
    harga_produk: 499000,
    persentase_diskon: 23,
    mata_uang: "IDR",
    jumlah_unit: 80,
    unit_terjual: 210,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 3.5,
    dimensi_produk: "45x35x20 cm",
    bahan: "Plastik HDPE + Baterai Lithium",
    negara_asal: "Indonesia",
    spesifikasi: "Sprayer otomatis 16L dengan baterai tahan 5 jam.",
    deskripsi_produk:
      "Sprayer elektrik untuk penyemprotan pupuk atau pestisida. Dilengkapi indikator baterai dan nozzle adjustable.",
    keyword: "sprayer elektrik, alat semprot pertanian",
    gambar_produk: "/asset/pertanian/sprayer1.jpg",
    thumbnail_produk: "/asset/pertanian/sprayer1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/sprayer1a.jpg",
      "/asset/pertanian/sprayer1b.jpg",
      "/asset/pertanian/sprayer1c.jpg",
    ],
    toko: "AgriTech Indonesia",
    rating_toko: 4.7,
    status_toko: "Official Store",
    lokasi_toko: "Yogyakarta",
    rating_bintang: 4.6,
    jumlah_ulasan: 290,
  },
  {
    ASIN: "AGRI-004",
    nama_produk: "Kotoran Kambing Kering Fermentasi",
    merek_produk: "EcoFarm",
    model_produk: "Pupuk Padat Organik",
    kategori: "Pertanian",
    sub_kategori: "Pupuk",
    harga_asli: 75000,
    harga_produk: 52000,
    persentase_diskon: 31,
    mata_uang: "IDR",
    jumlah_unit: 150,
    unit_terjual: 340,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 10,
    bahan: "Kotoran kambing fermentasi alami",
    negara_asal: "Indonesia",
    spesifikasi: "Memperbaiki struktur tanah, tanpa bau menyengat.",
    deskripsi_produk:
      "Pupuk kandang kambing fermentasi alami untuk berbagai tanaman. Mengandung unsur hara makro dan mikro yang dibutuhkan tanaman.",
    keyword: "pupuk kandang, pupuk organik padat",
    gambar_produk: "/asset/pertanian/pupuk2.jpg",
    thumbnail_produk: "/asset/pertanian/pupuk2a.jpg",
    galeri_gambar: [
      "/asset/pertanian/pupuk2a.jpg",
      "/asset/pertanian/pupuk2b.jpg",
      "/asset/pertanian/pupuk2c.jpg",
    ],
    toko: "EcoFarm Indonesia",
    rating_toko: 4.9,
    status_toko: "Toko Biasa",
    lokasi_toko: "Malang, Jawa Timur",
    rating_bintang: 4.8,
    jumlah_ulasan: 451,
  },
  {
    ASIN: "AGRI-005",
    nama_produk: "Polybag Tanaman Hitam 30x30cm",
    merek_produk: "GrowBag",
    model_produk: "Polybag Pertanian",
    kategori: "Pertanian",
    sub_kategori: "Peralatan Tanam",
    harga_asli: 50000,
    harga_produk: 35000,
    persentase_diskon: 30,
    mata_uang: "IDR",
    jumlah_unit: 500,
    unit_terjual: 1100,
    status_produk: "Tersedia",
    minimum_pemesanan: 10,
    kondisi_produk: "Baru",
    berat_satuan: 0.02,
    bahan: "Plastik tebal tahan UV",
    negara_asal: "Indonesia",
    spesifikasi: "Ukuran 30x30cm, isi 100 pcs.",
    deskripsi_produk:
      "Polybag hitam berkualitas untuk media tanam sayur, buah, atau tanaman hias. Tahan sinar matahari dan tidak mudah robek.",
    keyword: "polybag pertanian, media tanam",
    gambar_produk: "/asset/pertanian/polybag1.jpg",
    thumbnail_produk: "/asset/pertanian/polybag1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/polybag1a.jpg",
      "/asset/pertanian/polybag1b.jpg",
      "/asset/pertanian/polybag1c.jpg",
    ],
    toko: "GrowBag Store",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Kediri, Jawa Timur",
    rating_bintang: 4.6,
    jumlah_ulasan: 214,
  },
  {
    ASIN: "AGRI-006",
    nama_produk: "Traktor Mini Rotary 6.5HP",
    merek_produk: "TaniPro",
    model_produk: "Rotavator TR650",
    kategori: "Pertanian",
    sub_kategori: "Mesin Pertanian",
    harga_asli: 8500000,
    harga_produk: 7390000,
    persentase_diskon: 13,
    mata_uang: "IDR",
    jumlah_unit: 20,
    unit_terjual: 40,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 60,
    bahan: "Besi dan baja tahan karat",
    negara_asal: "Indonesia",
    spesifikasi: "Mesin bensin 6.5HP, lebar kerja 80cm.",
    deskripsi_produk:
      "Traktor mini serbaguna untuk pengolahan lahan pertanian kecil. Irit bahan bakar dan mudah dioperasikan.",
    keyword: "traktor mini, mesin pertanian",
    gambar_produk: "/asset/pertanian/traktor1.jpg",
    thumbnail_produk: "/asset/pertanian/traktor1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/traktor1a.jpg",
      "/asset/pertanian/traktor1b.jpg",
      "/asset/pertanian/traktor1c.jpg",
    ],
    toko: "TaniPro Machinery",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Solo, Jawa Tengah",
    rating_bintang: 4.8,
    jumlah_ulasan: 128,
  },
  {
    ASIN: "AGRI-007",
    nama_produk: "Net Paranet 65% Green",
    merek_produk: "AgriShade",
    model_produk: "Paranet 3x10m",
    kategori: "Pertanian",
    sub_kategori: "Perlengkapan",
    harga_asli: 180000,
    harga_produk: 135000,
    persentase_diskon: 25,
    mata_uang: "IDR",
    jumlah_unit: 100,
    unit_terjual: 260,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 2,
    bahan: "Polietilen UV Stabil",
    negara_asal: "Indonesia",
    spesifikasi: "Mengurangi sinar matahari 65%, cocok untuk pembibitan.",
    deskripsi_produk:
      "Paranet hijau 65% untuk melindungi tanaman dari paparan sinar matahari langsung. Tahan lama dan mudah dipasang.",
    keyword: "paranet, pelindung tanaman",
    gambar_produk: "/asset/pertanian/paranet1.jpg",
    thumbnail_produk: "/asset/pertanian/paranet1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/paranet1a.jpg",
      "/asset/pertanian/paranet1b.jpg",
      "/asset/pertanian/paranet1c.jpg",
    ],
    toko: "AgriShade Indonesia",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Kuningan, Jawa Barat",
    rating_bintang: 4.7,
    jumlah_ulasan: 274,
  },
  {
    ASIN: "AGRI-008",
    nama_produk: "Mulsa Plastik Silver Hitam",
    merek_produk: "TaniCover",
    model_produk: "Mulsa 1x400m",
    kategori: "Pertanian",
    sub_kategori: "Pelindung Tanaman",
    harga_asli: 310000,
    harga_produk: 255000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 60,
    unit_terjual: 140,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 8,
    bahan: "Plastik UV Silver-Black",
    negara_asal: "Indonesia",
    spesifikasi: "Lebar 1m panjang 400m, anti jamur.",
    deskripsi_produk:
      "Mulsa plastik dua sisi untuk menekan gulma dan menjaga kelembaban tanah. Cocok untuk sayuran dan melon.",
    keyword: "mulsa plastik, pertanian sayur",
    gambar_produk: "/asset/pertanian/mulsa1.jpg",
    thumbnail_produk: "/asset/pertanian/mulsa1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/mulsa1a.jpg",
      "/asset/pertanian/mulsa1b.jpg",
      "/asset/pertanian/mulsa1c.jpg",
    ],
    toko: "TaniCover Indonesia",
    rating_toko: 4.6,
    status_toko: "Toko Biasa",
    lokasi_toko: "Kediri, Jawa Timur",
    rating_bintang: 4.6,
    jumlah_ulasan: 192,
  },
  {
    ASIN: "AGRI-009",
    nama_produk: "Pestisida Nabati NeemOil",
    merek_produk: "BioTani",
    model_produk: "Neem Extract",
    kategori: "Pertanian",
    sub_kategori: "Pestisida Organik",
    harga_asli: 90000,
    harga_produk: 69000,
    persentase_diskon: 23,
    mata_uang: "IDR",
    jumlah_unit: 120,
    unit_terjual: 320,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.5,
    bahan: "Ekstrak biji nimba (Azadirachta indica)",
    negara_asal: "Indonesia",
    spesifikasi: "Efektif lawan kutu daun, ulat, dan jamur daun.",
    deskripsi_produk:
      "Pestisida alami berbasis minyak neem (nimba) yang aman bagi lingkungan dan tidak berbahaya bagi manusia.",
    keyword: "pestisida organik, neem oil",
    gambar_produk: "/asset/pertanian/neem1.jpg",
    thumbnail_produk: "/asset/pertanian/neem1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/neem1a.jpg",
      "/asset/pertanian/neem1b.jpg",
      "/asset/pertanian/neem1c.jpg",
    ],
    toko: "BioTani Organic",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 309,
  },
  {
    ASIN: "AGRI-010",
    nama_produk: "Greenhouse Mini Portable",
    merek_produk: "GrowHouse",
    model_produk: "GH-Mini",
    kategori: "Pertanian",
    sub_kategori: "Rumah Tanaman",
    harga_asli: 1200000,
    harga_produk: 999000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 25,
    unit_terjual: 70,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 15,
    bahan: "Rangka besi galvanis + plastik UV",
    negara_asal: "Indonesia",
    spesifikasi: "Ukuran 2x1.5x2m, cocok untuk hobi hidroponik.",
    deskripsi_produk:
      "Greenhouse mini untuk melindungi tanaman dari hujan dan sinar matahari berlebih. Cocok untuk urban farming dan hidroponik.",
    keyword: "greenhouse mini, rumah tanaman",
    gambar_produk: "/asset/pertanian/greenhouse1.jpg",
    thumbnail_produk: "/asset/pertanian/greenhouse1a.jpg",
    galeri_gambar: [
      "/asset/pertanian/greenhouse1a.jpg",
      "/asset/pertanian/greenhouse1b.jpg",
      "/asset/pertanian/greenhouse1c.jpg",
    ],
    toko: "GrowHouse Official",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Tangerang, Banten",
    rating_bintang: 4.9,
    jumlah_ulasan: 241,
  },

  // ELEKTRONIK
  {
    ASIN: "ELEC-001",
    nama_produk: "Smart TV LED 43 Inch Full HD",
    merek_produk: "VisioTech",
    model_produk: "VT-43FHD",
    kategori: "Elektronik",
    sub_kategori: "Televisi",
    harga_asli: 4299000,
    harga_produk: 3699000,
    persentase_diskon: 14,
    mata_uang: "IDR",
    jumlah_unit: 80,
    unit_terjual: 310,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 6.5,
    dimensi_produk: "96x60x10 cm",
    bahan: "Plastik dan logam",
    negara_asal: "Indonesia",
    spesifikasi: "Resolusi Full HD 1080p, Wi-Fi, YouTube & Netflix Ready.",
    deskripsi_produk:
      "Smart TV LED VisioTech 43 Inch menghadirkan tampilan tajam dan jernih dengan konektivitas Wi-Fi bawaan untuk streaming film favoritmu.",
    keyword: "smart tv, televisi full hd",
    gambar_produk: "/asset/elektronik/tv1.jpg",
    thumbnail_produk: "/asset/elektronik/tv1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/tv1a.jpg",
      "/asset/elektronik/tv1b.jpg",
      "/asset/elektronik/tv1c.jpg",
    ],
    toko: "VisioTech Official Store",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Utara",
    rating_bintang: 4.8,
    jumlah_ulasan: 1250,
  },
  {
    ASIN: "ELEC-002",
    nama_produk: "Kipas Angin Dinding Remote 16 Inch",
    merek_produk: "Maspion",
    model_produk: "WFR-1602",
    kategori: "Elektronik",
    sub_kategori: "Pendingin Ruangan",
    harga_asli: 549000,
    harga_produk: 449000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 150,
    unit_terjual: 620,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 3.2,
    bahan: "Plastik ABS",
    negara_asal: "Indonesia",
    spesifikasi: "3 kecepatan angin, kontrol remote, mode tidur.",
    deskripsi_produk:
      "Kipas dinding Maspion dengan remote control dan mode hemat energi. Ideal untuk kamar atau ruang kerja.",
    keyword: "kipas angin, kipas remote",
    gambar_produk: "/asset/elektronik/kipas1.jpg",
    thumbnail_produk: "/asset/elektronik/kipas1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/kipas1a.jpg",
      "/asset/elektronik/kipas1b.jpg",
      "/asset/elektronik/kipas1c.jpg",
    ],
    toko: "Maspion Official",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Surabaya",
    rating_bintang: 4.7,
    jumlah_ulasan: 970,
  },
  {
    ASIN: "ELEC-003",
    nama_produk: "Rice Cooker 1.8L Serbaguna",
    merek_produk: "Cosmos",
    model_produk: "CRJ-1801",
    kategori: "Elektronik",
    sub_kategori: "Peralatan Dapur",
    harga_asli: 499000,
    harga_produk: 385000,
    persentase_diskon: 23,
    mata_uang: "IDR",
    jumlah_unit: 200,
    unit_terjual: 1340,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 2.1,
    bahan: "Aluminium anti lengket",
    negara_asal: "Indonesia",
    spesifikasi: "Kapasitas 1.8L, fungsi cook & warm, hemat listrik.",
    deskripsi_produk:
      "Rice cooker serbaguna Cosmos untuk menanak nasi, mengukus, dan menjaga kehangatan makanan lebih lama.",
    keyword: "rice cooker, magic com cosmos",
    gambar_produk: "/asset/elektronik/ricecooker1.jpg",
    thumbnail_produk: "/asset/elektronik/ricecooker1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/ricecooker1a.jpg",
      "/asset/elektronik/ricecooker1b.jpg",
      "/asset/elektronik/ricecooker1c.jpg",
    ],
    toko: "Cosmos Official",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Bekasi",
    rating_bintang: 4.8,
    jumlah_ulasan: 1520,
  },
  {
    ASIN: "ELEC-004",
    nama_produk: "Blender Kaca 1.5L Turbo Pro",
    merek_produk: "Philips",
    model_produk: "HR2116",
    kategori: "Elektronik",
    sub_kategori: "Peralatan Dapur",
    harga_asli: 975000,
    harga_produk: 799000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 90,
    unit_terjual: 410,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 3.1,
    bahan: "Kaca + pisau stainless steel",
    negara_asal: "Indonesia",
    spesifikasi: "Motor 600W, 5 kecepatan, mode penghancur es.",
    deskripsi_produk:
      "Blender Philips dengan wadah kaca tahan panas dan pisau tajam. Cocok untuk jus, bumbu, dan smoothies.",
    keyword: "blender philips, blender kaca",
    gambar_produk: "/asset/elektronik/blender1.jpg",
    thumbnail_produk: "/asset/elektronik/blender1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/blender1a.jpg",
      "/asset/elektronik/blender1b.jpg",
      "/asset/elektronik/blender1c.jpg",
    ],
    toko: "Philips Indonesia",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.9,
    jumlah_ulasan: 840,
  },
  {
    ASIN: "ELEC-005",
    nama_produk: "Smartphone 5G 128GB RAM 8GB",
    merek_produk: "Realme",
    model_produk: "Realme 11 5G",
    kategori: "Elektronik",
    sub_kategori: "Handphone",
    harga_asli: 3899000,
    harga_produk: 3499000,
    persentase_diskon: 10,
    mata_uang: "IDR",
    jumlah_unit: 120,
    unit_terjual: 1050,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.3,
    bahan: "Aluminium + kaca Gorilla",
    negara_asal: "Indonesia",
    spesifikasi: "Layar 6.6” FHD+, kamera 108MP, baterai 5000mAh.",
    deskripsi_produk:
      "Smartphone 5G cepat dan elegan dengan kamera super jernih dan performa gaming ringan untuk aktivitas harian.",
    keyword: "hp realme, smartphone 5g",
    gambar_produk: "/asset/elektronik/hp1.jpg",
    thumbnail_produk: "/asset/elektronik/hp1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/hp1a.jpg",
      "/asset/elektronik/hp1b.jpg",
      "/asset/elektronik/hp1c.jpg",
    ],
    toko: "Realme Official Store",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta",
    rating_bintang: 4.9,
    jumlah_ulasan: 5200,
  },
  {
    ASIN: "ELEC-006",
    nama_produk: "Headset Wireless ANC",
    merek_produk: "Sony",
    model_produk: "WH-CH720N",
    kategori: "Elektronik",
    sub_kategori: "Aksesoris Audio",
    harga_asli: 2099000,
    harga_produk: 1799000,
    persentase_diskon: 14,
    mata_uang: "IDR",
    jumlah_unit: 60,
    unit_terjual: 330,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.25,
    bahan: "Plastik premium",
    negara_asal: "Malaysia",
    spesifikasi: "Noise Cancelling, Bluetooth 5.3, baterai 35 jam.",
    deskripsi_produk:
      "Headset wireless Sony dengan fitur Active Noise Cancelling dan suara jernih untuk musik maupun panggilan.",
    keyword: "headset sony, wireless headphone",
    gambar_produk: "/asset/elektronik/headset1.jpg",
    thumbnail_produk: "/asset/elektronik/headset1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/headset1a.jpg",
      "/asset/elektronik/headset1b.jpg",
      "/asset/elektronik/headset1c.jpg",
    ],
    toko: "Sony Audio Store",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Pusat",
    rating_bintang: 4.9,
    jumlah_ulasan: 2110,
  },
  {
    ASIN: "ELEC-007",
    nama_produk: "Laptop 14 Inch Ryzen 5 SSD 512GB",
    merek_produk: "ASUS",
    model_produk: "VivoBook M415",
    kategori: "Elektronik",
    sub_kategori: "Komputer",
    harga_asli: 8299000,
    harga_produk: 7599000,
    persentase_diskon: 8,
    mata_uang: "IDR",
    jumlah_unit: 40,
    unit_terjual: 200,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 1.5,
    bahan: "Aluminium",
    negara_asal: "Indonesia",
    spesifikasi: "Ryzen 5 5500U, 8GB RAM, SSD 512GB, Win11.",
    deskripsi_produk:
      "Laptop ringan dan cepat untuk kerja dan kuliah. Dilengkapi layar jernih dan baterai tahan lama.",
    keyword: "laptop asus, vivobook ryzen",
    gambar_produk: "/asset/elektronik/laptop1.jpg",
    thumbnail_produk: "/asset/elektronik/laptop1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/laptop1a.jpg",
      "/asset/elektronik/laptop1b.jpg",
      "/asset/elektronik/laptop1c.jpg",
    ],
    toko: "ASUS Official Store",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Bandung",
    rating_bintang: 4.9,
    jumlah_ulasan: 980,
  },
  {
    ASIN: "ELEC-008",
    nama_produk: "Smartwatch Fitness Tracker",
    merek_produk: "Xiaomi",
    model_produk: "Mi Band 8",
    kategori: "Elektronik",
    sub_kategori: "Wearable",
    harga_asli: 699000,
    harga_produk: 579000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 300,
    unit_terjual: 1400,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.04,
    bahan: "TPU + Aluminium",
    negara_asal: "China",
    spesifikasi: "Layar AMOLED, detak jantung, notifikasi smartphone.",
    deskripsi_produk:
      "Smartwatch Xiaomi ringan dengan fitur pelacak kesehatan lengkap dan daya baterai hingga 10 hari.",
    keyword: "mi band 8, smartwatch xiaomi",
    gambar_produk: "/asset/elektronik/smartwatch1.jpg",
    thumbnail_produk: "/asset/elektronik/smartwatch1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/smartwatch1a.jpg",
      "/asset/elektronik/smartwatch1b.jpg",
      "/asset/elektronik/smartwatch1c.jpg",
    ],
    toko: "Xiaomi Official Store",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Tangerang",
    rating_bintang: 4.8,
    jumlah_ulasan: 3100,
  },
  {
    ASIN: "ELEC-009",
    nama_produk: "Kamera Mirrorless 24MP 4K",
    merek_produk: "Canon",
    model_produk: "EOS M50 Mark II",
    kategori: "Elektronik",
    sub_kategori: "Kamera",
    harga_asli: 10499000,
    harga_produk: 9499000,
    persentase_diskon: 10,
    mata_uang: "IDR",
    jumlah_unit: 25,
    unit_terjual: 180,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.4,
    bahan: "Magnesium Alloy",
    negara_asal: "Jepang",
    spesifikasi: "Sensor 24MP APS-C, video 4K, Wi-Fi & mic input.",
    deskripsi_produk:
      "Kamera mirrorless ringkas dengan hasil foto profesional, cocok untuk vlog dan konten kreator.",
    keyword: "kamera mirrorless canon, eos m50",
    gambar_produk: "/asset/elektronik/kamera1.jpg",
    thumbnail_produk: "/asset/elektronik/kamera1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/kamera1a.jpg",
      "/asset/elektronik/kamera1b.jpg",
      "/asset/elektronik/kamera1c.jpg",
    ],
    toko: "Canon Indonesia",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Barat",
    rating_bintang: 4.9,
    jumlah_ulasan: 455,
  },
  {
    ASIN: "ELEC-010",
    nama_produk: "Speaker Bluetooth Bass Pro",
    merek_produk: "JBL",
    model_produk: "Flip 6",
    kategori: "Elektronik",
    sub_kategori: "Audio",
    harga_asli: 2299000,
    harga_produk: 1999000,
    persentase_diskon: 13,
    mata_uang: "IDR",
    jumlah_unit: 100,
    unit_terjual: 490,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.55,
    bahan: "Karet dan mesh fabric",
    negara_asal: "China",
    spesifikasi: "IP67 waterproof, 12 jam playtime, Bluetooth 5.1.",
    deskripsi_produk:
      "Speaker portable JBL Flip 6 dengan bass mantap dan desain tangguh untuk indoor maupun outdoor.",
    keyword: "speaker bluetooth, jbl flip",
    gambar_produk: "/asset/elektronik/speaker1.jpg",
    thumbnail_produk: "/asset/elektronik/speaker1a.jpg",
    galeri_gambar: [
      "/asset/elektronik/speaker1a.jpg",
      "/asset/elektronik/speaker1b.jpg",
      "/asset/elektronik/speaker1c.jpg",
    ],
    toko: "JBL Official Audio",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.9,
    jumlah_ulasan: 1670,
  },

    // FURNITURE
  {
    ASIN: "FURN-ID-001",
    nama_produk: "Meja Kayu Jati Solid",
    merek_produk: "JeparaCraft",
    model_produk: "JC-MJ100",
    kategori: "Furnitur",
    sub_kategori: "Meja",
    harga_asli: 2500000,
    harga_produk: 1999000,
    persentase_diskon: 20,
    mata_uang: "IDR",
    jumlah_unit: 50,
    unit_terjual: 320,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 25,
    dimensi_produk: "150x80x75 cm",
    bahan: "Kayu Jati",
    warna: "Cokelat Tua",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Meja kayu jati solid dengan desain minimalis modern buatan pengrajin Jepara. Tahan lama, anti rayap, dan cocok untuk ruang makan atau ruang kerja.",
    gambar_produk: "/images/furnitur/meja-jati.jpg",
    thumbnail_produk: "/images/furnitur/thumb/meja-jati1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/meja-jati2.jpg",
      "/images/furnitur/thumb/meja-jati3.jpg",
      "/images/furnitur/thumb/meja-jati4.jpg"
    ],
    toko: "Jepara Mebel Asli",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jepara, Jawa Tengah",
    rating_bintang: 4.8,
    jumlah_ulasan: 540
  },
  {
    ASIN: "FURN-ID-002",
    nama_produk: "Kursi Rotan Sintetis",
    merek_produk: "RattanHome",
    model_produk: "RH-KRS01",
    kategori: "Furnitur",
    sub_kategori: "Kursi",
    harga_asli: 800000,
    harga_produk: 699000,
    persentase_diskon: 13,
    mata_uang: "IDR",
    jumlah_unit: 120,
    unit_terjual: 850,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 5,
    bahan: "Rotan Sintetis & Rangka Besi",
    warna: "Cokelat Muda",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Kursi rotan sintetis yang elegan dan tahan cuaca, cocok untuk teras atau ruang santai. Buatan tangan pengrajin Cirebon.",
    gambar_produk: "/images/furnitur/kursi-rotan.jpg",
    thumbnail_produk: "/images/furnitur/thumb/kursi-rotan1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/kursi-rotan2.jpg",
      "/images/furnitur/thumb/kursi-rotan3.jpg",
      "/images/furnitur/thumb/kursi-rotan4.jpg"
    ],
    toko: "Rattan Art Cirebon",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Cirebon, Jawa Barat",
    rating_bintang: 4.6,
    jumlah_ulasan: 310
  },
  {
    ASIN: "FURN-ID-003",
    nama_produk: "Lemari Pakaian 3 Pintu Sliding",
    merek_produk: "Mebelindo",
    model_produk: "MI-LM3P",
    kategori: "Furnitur",
    sub_kategori: "Lemari",
    harga_asli: 3200000,
    harga_produk: 2899000,
    persentase_diskon: 10,
    mata_uang: "IDR",
    jumlah_unit: 30,
    unit_terjual: 180,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 65,
    dimensi_produk: "180x60x200 cm",
    bahan: "Kayu MDF Laminasi",
    warna: "Putih",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Lemari pakaian modern dengan pintu geser, dilengkapi cermin dan rak penyimpanan ekstra. Desain minimalis cocok untuk kamar modern.",
    gambar_produk: "/images/furnitur/lemari-pakaian.jpg",
    thumbnail_produk: "/images/furnitur/thumb/lemari-pakaian1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/lemari-pakaian2.jpg",
      "/images/furnitur/thumb/lemari-pakaian3.jpg",
      "/images/furnitur/thumb/lemari-pakaian4.jpg"
    ],
    toko: "Mebelindo Store",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.7,
    jumlah_ulasan: 270
  },
  {
    ASIN: "FURN-ID-004",
    nama_produk: "Rak Buku Minimalis",
    merek_produk: "SundaFurni",
    model_produk: "SF-RB01",
    kategori: "Furnitur",
    sub_kategori: "Rak Buku",
    harga_asli: 950000,
    harga_produk: 789000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 100,
    unit_terjual: 650,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 15,
    dimensi_produk: "120x30x180 cm",
    bahan: "Kayu Mahoni",
    warna: "Cokelat Natural",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Rak buku minimalis bergaya skandinavia dengan finishing halus. Cocok untuk ruang kerja atau ruang tamu.",
    gambar_produk: "/images/furnitur/rak-buku.jpg",
    thumbnail_produk: "/images/furnitur/thumb/rak-buku1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/rak-buku2.jpg",
      "/images/furnitur/thumb/rak-buku3.jpg",
      "/images/furnitur/thumb/rak-buku4.jpg"
    ],
    toko: "Furni Sunda",
    rating_toko: 4.5,
    status_toko: "Toko Biasa",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.6,
    jumlah_ulasan: 190
  },
  {
    ASIN: "FURN-ID-005",
    nama_produk: "Sofa L Bentuk Klasik",
    merek_produk: "Eleganza",
    model_produk: "ELG-SFL",
    kategori: "Furnitur",
    sub_kategori: "Sofa",
    harga_asli: 7000000,
    harga_produk: 6499000,
    persentase_diskon: 7,
    mata_uang: "IDR",
    jumlah_unit: 20,
    unit_terjual: 90,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 80,
    bahan: "Kain Beludru & Kayu Jati",
    warna: "Abu-abu Tua",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Sofa berbentuk L dengan bahan beludru premium dan rangka jati solid. Nyaman dan mewah, cocok untuk ruang keluarga modern.",
    gambar_produk: "/images/furnitur/sofa-l.jpg",
    thumbnail_produk: "/images/furnitur/thumb/sofa-l1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/sofa-l2.jpg",
      "/images/furnitur/thumb/sofa-l3.jpg",
      "/images/furnitur/thumb/sofa-l4.jpg"
    ],
    toko: "Eleganza Living",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.8,
    jumlah_ulasan: 310
  },
  {
    ASIN: "FURN-ID-006",
    nama_produk: "Tempat Tidur Kayu Minimalis",
    merek_produk: "KayuAsri",
    model_produk: "KA-TT01",
    kategori: "Furnitur",
    sub_kategori: "Tempat Tidur",
    harga_asli: 3900000,
    harga_produk: 3499000,
    persentase_diskon: 10,
    mata_uang: "IDR",
    jumlah_unit: 25,
    unit_terjual: 200,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 60,
    bahan: "Kayu Jati & MDF",
    warna: "Cokelat Tua",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Tempat tidur kayu dengan desain minimalis dan kokoh. Finishing natural dengan headboard elegan.",
    gambar_produk: "/images/furnitur/tempat-tidur.jpg",
    thumbnail_produk: "/images/furnitur/thumb/tempat-tidur1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/tempat-tidur2.jpg",
      "/images/furnitur/thumb/tempat-tidur3.jpg",
      "/images/furnitur/thumb/tempat-tidur4.jpg"
    ],
    toko: "Kayu Asri Mebel",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Jepara, Jawa Tengah",
    rating_bintang: 4.7,
    jumlah_ulasan: 220
  },
  {
    ASIN: "FURN-ID-007",
    nama_produk: "Meja TV Modern Minimalis",
    merek_produk: "Moderno",
    model_produk: "MD-TV01",
    kategori: "Furnitur",
    sub_kategori: "Meja TV",
    harga_asli: 1750000,
    harga_produk: 1499000,
    persentase_diskon: 14,
    mata_uang: "IDR",
    jumlah_unit: 40,
    unit_terjual: 300,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 22,
    bahan: "Kayu MDF & Besi",
    warna: "Hitam",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Meja TV dengan kombinasi kayu dan besi. Desain modern dan kokoh, cocok untuk ruang keluarga bergaya industrial.",
    gambar_produk: "/images/furnitur/meja-tv.jpg",
    thumbnail_produk: "/images/furnitur/thumb/meja-tv1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/meja-tv2.jpg",
      "/images/furnitur/thumb/meja-tv3.jpg",
      "/images/furnitur/thumb/meja-tv4.jpg"
    ],
    toko: "Moderno Living",
    rating_toko: 4.6,
    status_toko: "Toko Biasa",
    lokasi_toko: "Surabaya, Jawa Timur",
    rating_bintang: 4.5,
    jumlah_ulasan: 170
  },
  {
    ASIN: "FURN-ID-008",
    nama_produk: "Kabinet Dapur Custom",
    merek_produk: "DapurAsri",
    model_produk: "DA-KBC",
    kategori: "Furnitur",
    sub_kategori: "Kabinet Dapur",
    harga_asli: 8000000,
    harga_produk: 7499000,
    persentase_diskon: 6,
    mata_uang: "IDR",
    jumlah_unit: 10,
    unit_terjual: 60,
    status_produk: "Pre-order",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 90,
    bahan: "Kayu Jati Belanda & Granit",
    warna: "Putih & Abu",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Kabinet dapur custom dengan desain elegan dan finishing glossy. Dapat disesuaikan ukuran dan warna sesuai pesanan.",
    gambar_produk: "/images/furnitur/kabinet-dapur.jpg",
    thumbnail_produk: "/images/furnitur/thumb/kabinet-dapur1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/kabinet-dapur2.jpg",
      "/images/furnitur/thumb/kabinet-dapur3.jpg",
      "/images/furnitur/thumb/kabinet-dapur4.jpg"
    ],
    toko: "Dapur Asri Design",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Tangerang, Banten",
    rating_bintang: 4.8,
    jumlah_ulasan: 95
  },
  {
    ASIN: "FURN-ID-009",
    nama_produk: "Cermin Dinding Bulat Kayu",
    merek_produk: "Mirrorly",
    model_produk: "MR-BLK01",
    kategori: "Furnitur",
    sub_kategori: "Dekorasi",
    harga_asli: 550000,
    harga_produk: 449000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 200,
    unit_terjual: 900,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 3,
    bahan: "Kayu Pinus & Kaca",
    warna: "Natural",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Cermin dinding dengan bingkai kayu alami buatan tangan. Memberi kesan luas dan hangat pada ruangan.",
    gambar_produk: "/images/furnitur/cermin-bulat.jpg",
    thumbnail_produk: "/images/furnitur/thumb/cermin-bulat1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/cermin-bulat2.jpg",
      "/images/furnitur/thumb/cermin-bulat3.jpg",
      "/images/furnitur/thumb/cermin-bulat4.jpg"
    ],
    toko: "Mirrorly Studio",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.6,
    jumlah_ulasan: 410
  },
  {
    ASIN: "FURN-ID-010",
    nama_produk: "Bangku Panjang Teras",
    merek_produk: "TerasJati",
    model_produk: "TJ-BKT01",
    kategori: "Furnitur",
    sub_kategori: "Bangku",
    harga_asli: 1100000,
    harga_produk: 999000,
    persentase_diskon: 9,
    mata_uang: "IDR",
    jumlah_unit: 80,
    unit_terjual: 450,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 15,
    bahan: "Kayu Jati Tua",
    warna: "Cokelat Gelap",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Bangku panjang klasik dari kayu jati tua, cocok untuk area outdoor atau teras rumah. Tahan cuaca dan awet.",
    gambar_produk: "/images/furnitur/bangku-teras.jpg",
    thumbnail_produk: "/images/furnitur/thumb/bangku-teras1.jpg",
    galeri_gambar: [
      "/images/furnitur/thumb/bangku-teras2.jpg",
      "/images/furnitur/thumb/bangku-teras3.jpg",
      "/images/furnitur/thumb/bangku-teras4.jpg"
    ],
    toko: "Jepara Classic Wood",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Jepara, Jawa Tengah",
    rating_bintang: 4.7,
    jumlah_ulasan: 260
  },

    // EDUKASI
  {
    ASIN: "EDU-ID-001",
    nama_produk: "Buku Anak Cerdas: Petualangan di Nusantara",
    merek_produk: "Cendekia Press",
    model_produk: "CP-BAC01",
    kategori: "Edukasi",
    sub_kategori: "Buku Anak",
    harga_asli: 95000,
    harga_produk: 75000,
    persentase_diskon: 21,
    mata_uang: "IDR",
    jumlah_unit: 500,
    unit_terjual: 2200,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.3,
    bahan: "Kertas Art Paper Premium",
    warna: "Full Color",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Buku bergambar interaktif yang mengenalkan budaya dan keanekaragaman Nusantara untuk anak usia 4–8 tahun. Dilengkapi ilustrasi menarik dan aktivitas belajar ringan.",
    gambar_produk: "/images/edukasi/buku-anak-nusantara.jpg",
    thumbnail_produk: "/images/edukasi/thumb/buku-anak1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/buku-anak2.jpg",
      "/images/edukasi/thumb/buku-anak3.jpg",
      "/images/edukasi/thumb/buku-anak4.jpg"
    ],
    toko: "Toko Buku Cendekia",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Yogyakarta",
    rating_bintang: 4.8,
    jumlah_ulasan: 980
  },
  {
    ASIN: "EDU-ID-002",
    nama_produk: "Kelas Online: Desain Grafis Dasar",
    merek_produk: "SkillHub Indonesia",
    model_produk: "SH-DG01",
    kategori: "Edukasi",
    sub_kategori: "Kursus Online",
    harga_asli: 350000,
    harga_produk: 275000,
    persentase_diskon: 22,
    mata_uang: "IDR",
    jumlah_unit: 9999,
    unit_terjual: 5400,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Kelas online interaktif belajar desain grafis menggunakan Canva dan Photoshop. Cocok untuk pemula yang ingin memulai karier di bidang kreatif.",
    gambar_produk: "/images/edukasi/kelas-desain-grafis.jpg",
    thumbnail_produk: "/images/edukasi/thumb/kelas-desain1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/kelas-desain2.jpg",
      "/images/edukasi/thumb/kelas-desain3.jpg",
      "/images/edukasi/thumb/kelas-desain4.jpg"
    ],
    toko: "SkillHub ID",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Selatan",
    rating_bintang: 4.7,
    jumlah_ulasan: 680
  },
  {
    ASIN: "EDU-ID-003",
    nama_produk: "Mainan Edukasi Kayu: Puzzle Huruf Alfabet",
    merek_produk: "SmartWood",
    model_produk: "SW-PA01",
    kategori: "Edukasi",
    sub_kategori: "Mainan Edukasi",
    harga_asli: 150000,
    harga_produk: 125000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 300,
    unit_terjual: 1200,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 1.2,
    bahan: "Kayu Pinus",
    warna: "Berwarna-warni",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Puzzle alfabet dari kayu ramah lingkungan dengan cat aman untuk anak-anak. Membantu mengenal huruf dan koordinasi tangan-mata.",
    gambar_produk: "/images/edukasi/puzzle-huruf.jpg",
    thumbnail_produk: "/images/edukasi/thumb/puzzle-huruf1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/puzzle-huruf2.jpg",
      "/images/edukasi/thumb/puzzle-huruf3.jpg",
      "/images/edukasi/thumb/puzzle-huruf4.jpg"
    ],
    toko: "SmartWood Toys",
    rating_toko: 4.8,
    status_toko: "Toko Biasa",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.7,
    jumlah_ulasan: 520
  },
  {
    ASIN: "EDU-ID-004",
    nama_produk: "Modul Belajar Bahasa Inggris Anak",
    merek_produk: "EduKid",
    model_produk: "EK-ENG01",
    kategori: "Edukasi",
    sub_kategori: "Modul Belajar",
    harga_asli: 120000,
    harga_produk: 89000,
    persentase_diskon: 26,
    mata_uang: "IDR",
    jumlah_unit: 400,
    unit_terjual: 1700,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.5,
    bahan: "Kertas Art Carton",
    warna: "Full Color",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Modul belajar interaktif bahasa Inggris dasar untuk anak SD. Disertai latihan kosakata, audio, dan QR code untuk video pembelajaran.",
    gambar_produk: "/images/edukasi/modul-english.jpg",
    thumbnail_produk: "/images/edukasi/thumb/modul-eng1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/modul-eng2.jpg",
      "/images/edukasi/thumb/modul-eng3.jpg",
      "/images/edukasi/thumb/modul-eng4.jpg"
    ],
    toko: "EduKid Official",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Depok, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 860
  },
  {
    ASIN: "EDU-ID-005",
    nama_produk: "Paket Belajar Arduino Dasar",
    merek_produk: "TeknoLab",
    model_produk: "TL-ARD01",
    kategori: "Edukasi",
    sub_kategori: "Kit Elektronik",
    harga_asli: 550000,
    harga_produk: 499000,
    persentase_diskon: 9,
    mata_uang: "IDR",
    jumlah_unit: 200,
    unit_terjual: 950,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 1.5,
    bahan: "PCB & Komponen Elektronik",
    warna: "Biru",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Paket lengkap untuk belajar Arduino: board, kabel, sensor, dan panduan proyek berbasis STEM. Cocok untuk pelajar dan mahasiswa teknik.",
    gambar_produk: "/images/edukasi/arduino-kit.jpg",
    thumbnail_produk: "/images/edukasi/thumb/arduino1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/arduino2.jpg",
      "/images/edukasi/thumb/arduino3.jpg",
      "/images/edukasi/thumb/arduino4.jpg"
    ],
    toko: "TeknoLab Indonesia",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Surabaya, Jawa Timur",
    rating_bintang: 4.7,
    jumlah_ulasan: 410
  },
  {
    ASIN: "EDU-ID-006",
    nama_produk: "Poster Edukasi: Sistem Tata Surya",
    merek_produk: "VisualLearn",
    model_produk: "VL-STS01",
    kategori: "Edukasi",
    sub_kategori: "Poster Belajar",
    harga_asli: 75000,
    harga_produk: 59000,
    persentase_diskon: 21,
    mata_uang: "IDR",
    jumlah_unit: 700,
    unit_terjual: 1800,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.2,
    bahan: "Art Paper Laminasi Doff",
    warna: "Full Color",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Poster edukatif berwarna yang menjelaskan sistem tata surya dengan ilustrasi planet yang menarik. Cocok untuk sekolah dan rumah.",
    gambar_produk: "/images/edukasi/poster-tata-surya.jpg",
    thumbnail_produk: "/images/edukasi/thumb/poster1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/poster2.jpg",
      "/images/edukasi/thumb/poster3.jpg",
      "/images/edukasi/thumb/poster4.jpg"
    ],
    toko: "VisualLearn Store",
    rating_toko: 4.7,
    status_toko: "Toko Biasa",
    lokasi_toko: "Semarang, Jawa Tengah",
    rating_bintang: 4.6,
    jumlah_ulasan: 290
  },
  {
    ASIN: "EDU-ID-007",
    nama_produk: "Kursus Online: Public Speaking Confidence",
    merek_produk: "TalkPro ID",
    model_produk: "TP-PS01",
    kategori: "Edukasi",
    sub_kategori: "Kursus Online",
    harga_asli: 450000,
    harga_produk: 399000,
    persentase_diskon: 11,
    mata_uang: "IDR",
    jumlah_unit: 9999,
    unit_terjual: 1200,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0,
    deskripsi_produk:
      "Pelatihan public speaking berbasis video dan praktik langsung bersama mentor profesional. Dilengkapi sertifikat resmi.",
    gambar_produk: "/images/edukasi/public-speaking.jpg",
    thumbnail_produk: "/images/edukasi/thumb/public-speaking1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/public-speaking2.jpg",
      "/images/edukasi/thumb/public-speaking3.jpg",
      "/images/edukasi/thumb/public-speaking4.jpg"
    ],
    toko: "TalkPro Academy",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Pusat",
    rating_bintang: 4.8,
    jumlah_ulasan: 760
  },
  {
    ASIN: "EDU-ID-008",
    nama_produk: "Flashcard Bahasa Indonesia",
    merek_produk: "LittleLang",
    model_produk: "LL-ID01",
    kategori: "Edukasi",
    sub_kategori: "Flashcard",
    harga_asli: 85000,
    harga_produk: 69000,
    persentase_diskon: 18,
    mata_uang: "IDR",
    jumlah_unit: 400,
    unit_terjual: 1300,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.4,
    bahan: "Art Carton",
    warna: "Full Color",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Flashcard edukatif dengan gambar dan kata dalam Bahasa Indonesia. Cocok untuk anak prasekolah untuk memperluas kosa kata.",
    gambar_produk: "/images/edukasi/flashcard-bahasa.jpg",
    thumbnail_produk: "/images/edukasi/thumb/flashcard1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/flashcard2.jpg",
      "/images/edukasi/thumb/flashcard3.jpg",
      "/images/edukasi/thumb/flashcard4.jpg"
    ],
    toko: "LittleLang Indonesia",
    rating_toko: 4.8,
    status_toko: "Official Store",
    lokasi_toko: "Denpasar, Bali",
    rating_bintang: 4.7,
    jumlah_ulasan: 420
  },
  {
    ASIN: "EDU-ID-009",
    nama_produk: "Buku Panduan UMKM Digital",
    merek_produk: "BisnisCerdas",
    model_produk: "BC-UMKM01",
    kategori: "Edukasi",
    sub_kategori: "Buku Bisnis",
    harga_asli: 120000,
    harga_produk: 99000,
    persentase_diskon: 17,
    mata_uang: "IDR",
    jumlah_unit: 300,
    unit_terjual: 950,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 0.6,
    bahan: "Kertas Ivory",
    warna: "Full Color",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Panduan lengkap membangun usaha mikro di era digital. Dilengkapi studi kasus, strategi pemasaran online, dan tips branding.",
    gambar_produk: "/images/edukasi/buku-umkm.jpg",
    thumbnail_produk: "/images/edukasi/thumb/buku-umkm1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/buku-umkm2.jpg",
      "/images/edukasi/thumb/buku-umkm3.jpg",
      "/images/edukasi/thumb/buku-umkm4.jpg"
    ],
    toko: "BisnisCerdas Publisher",
    rating_toko: 4.9,
    status_toko: "Official Store",
    lokasi_toko: "Jakarta Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 530
  },
  {
    ASIN: "EDU-ID-010",
    nama_produk: "Set Alat Musik Angklung Edukatif",
    merek_produk: "Saung Angklung",
    model_produk: "SA-ANG01",
    kategori: "Edukasi",
    sub_kategori: "Alat Musik",
    harga_asli: 450000,
    harga_produk: 399000,
    persentase_diskon: 11,
    mata_uang: "IDR",
    jumlah_unit: 50,
    unit_terjual: 270,
    status_produk: "Tersedia",
    minimum_pemesanan: 1,
    kondisi_produk: "Baru",
    berat_satuan: 3,
    bahan: "Bambu Pilihan",
    warna: "Cokelat Natural",
    negara_asal: "Indonesia",
    deskripsi_produk:
      "Set angklung edukatif untuk anak sekolah, membantu belajar musik tradisional dan mengenal budaya Indonesia.",
    gambar_produk: "/images/edukasi/angklung.jpg",
    thumbnail_produk: "/images/edukasi/thumb/angklung1.jpg",
    galeri_gambar: [
      "/images/edukasi/thumb/angklung2.jpg",
      "/images/edukasi/thumb/angklung3.jpg",
      "/images/edukasi/thumb/angklung4.jpg"
    ],
    toko: "Saung Angklung Bandung",
    rating_toko: 4.9,
    status_toko: "Toko Biasa",
    lokasi_toko: "Bandung, Jawa Barat",
    rating_bintang: 4.8,
    jumlah_ulasan: 240
  }

  ];

  await uploadProducts(products);

  // 🔍 Cek semua produk setelah upload
  let all = await getAllProducts();
  console.log("📦 Produk setelah upload:");
  console.table(all);


  // Update satu produk
  // if (all.length > 0) {
  //   await updateProduct(all[0].id, {
  //     nama_produk: "Shampo Herbal Premium",
  //     harga_produk: 59900,
  //     jumlah_unit: 50,
  //   });
  // }


  // BulkUpdate (buat update pake mapping)
  // if (all.length >= 2) {
  //   await bulkUpdateProducts([
  //     { id: all[0].id, data: { persentase_diskon: 10, harga_produk: 54900 } },
  //     { id: all[1].id, data: { status_produk: "Habis", unit_terjual: 2000 } },
  //   ]);
  // }


  // Hapus satu produk
  // if (all.length > 0) {
  //   await deleteProduct(all[0].id);
  //   console.log(`🗑️ Produk ${all[0].nama_produk} berhasil dihapus`);
  // }


  // hapus semua produk
  // await deleteAllProducts();
  // console.log("🧹 Semua produk berhasil dihapus");


  // Cek hasi akhir
  // const final = await getAllProducts();
  // console.table(final);
}

seedProduk()
  .then(() => console.log("🌱 Selesai seeding"))
  .catch((err) => console.error("❌ Gagal seeding:", err));
